export const SERVICES_BATCH_3: Record<string, any> = {
  "Sainte-Adèle": {
    "posePart1": "Au centre névralgique culturel de la région, réaliser le remplacement de toiture à Sainte-Adèle consiste à dompter à la fois les forts reliefs rocailleux et le respect de ces pignons pittoresques. C'est en délaissant un matériau inférieur pour l'excellence de l'asphalte architecturale multicouches que l'allure d'antan des toits escarpés fusionne aux exigences d'isolation d'aujourd'hui.",
    "posePart2": "Le travail du chirurgien immobilier à Sainte-Adèle commence au décapage entier du vieux revêtement vers les assises. On nettoie rigoureusement, laissant nos maîtres évaluer s'il y eut détrempe de panel ou affaissement structurel dans ces denses secteurs isolés, le réparateur rectifie tout en l'infaillible plancher que vos garanties exigent pour l'épanouissement futur.",
    "posePart3": "La pose intègre l'installation magistrale d'un larmier continu sous l'apposition énorme de membranes thermocollantes s'imbriquant parfaitement. Dans les grandes élévations de Sainte-Adèle, empêcher le froid figeant aux bords, de repousser la neige dans la toiture est crucial. Notre science sur la pose et calibration de ventilation mécanique et gravitationnelles assène le coup de grâce contre ces défaillances de digues.",
    "repPart1": "Un blizzard intense sur ces escarpements rocheux et un vent du nord viennent de décaper le couvercle de la maison. C'est l'urgence où vous agissez à Sainte-Adèle pour inviter Toiture Jonathan Délisle. Sans délai et au sommet de nos compétences, notre sécurisation immédiate et intègre protège la résidence par lourdes membranes d'hiver imperméables.",
    "repPart2": "Réparer les vieilles demeures à Sainte-Adèle veut dire se faufiler dans la ruse de l'eau. Une cheminée de pierres désaffectée, le croisement de deux bâtisses créant une fente désastreuse. Nous exhumons le bardeau fatigué avec grande adresse, rétablissant les nouveaux solins d'aluminium et fixant de parfaits agencements asphalte harmonieux qui feront oublier ce malicieux épisode d'eau."
  },
  "Sainte-Agathe-des-Monts": {
    "posePart1": "L'ampleur climatique colossale que connaît le remplacement de la toiture à Sainte-Agathe-des-Monts nous amène résolument vers des protections haut de gamme, sans jamais sous-dimensionner leur capacité. Dotant son climat de glaciations parmi les pires et bordées records, la protection des chalets en revêtement d'asphalte architectural lourd s'y affirme comme l'authentique muraille de forteresse estivale et hivernale.",
    "posePart2": "Avec un immense parc immobilier de charmes ancestraux et chics côtoyer ces froids profonds, retirer l'entier d'un bardeau fatigué met en évidence toute cicatrice dissimulée au bois de soutient de Sainte-Agathe. Pas de fausse étape ici : redressement, vissage, arrachage complet du support spongieux, les professionnels reconstituent votre paix de l'esprit à renfort de travaux robustes.",
    "posePart3": "Face aux barrages de glaces (cauchemars récurrents du coin), notre solution appliquée à Sainte-Agathe pose deux fois plus larges de feuilles d'adhérence élastomères d'avant de tuiles. Ce grand barrage contre l'implacable froid garantit qu'il n'y aura nulle fusion destructrice. Le tout cloué aux attaches redoublées se conjugue dans l'excellence en propulsant à terme toute la touffeur piégée, grâce a ces imposants conduits aérés.",
    "repPart1": "La réalité d'un toit endommagé a Sainte-Agathe par un arbre plié ou d'un solin décalotté peut être brutal. Avec nous l'infortune de la fuite et d'immenses coulisses a le plafond est aussitôt neutralisée en urgence sans conditions par notre corps expéditionnaire; de bâches scellées ou ancrages d'obstruction arrêtent la calamité purement.",
    "repPart2": "Aucun goudron de fortune posé grossièrement ne fera. À Sainte-Agathe-des-Monts la délicatesse d'un expert couvreur scrute et rehausse le périmètre détruit de votre lucarne ou aérateur grugé, rattachant la structure à d'invisibles réparations avec tuiles de grade ultime. Le résultat visuel en toiture garantit zéro réplique."
  },
  "Sainte-Anne-des-Lacs": {
    "posePart1": "Remplacer ces vieilles toitures qui ornent les sinueux lacs cachés de Sainte-Anne-des-Lacs, c'est batailler contre l'humide nature. Dans les sous-bois où les chalets sont magnifiés, on implante ces lourds revêtements architecturaux d'asphalte infusés de cuivres algicides réprimant la croissance de moisissure fétide et offrant les belles couleurs en harmonie à ce silence absolu.",
    "posePart2": "Notre professionnalisme ne connait l'à-peu-près; la déconstruction totale de l'asphalte altéré par ce manque critique d'ensoleillement évacue vos troubles. À Sainte-Anne, nous examinons ce contreplaqué très souvent confiné à sa mort prématurée par le manque d'aération, le réhabilitons par la menuiserie noble et réalignons ces toits forestiers en parfaite intégrité.",
    "posePart3": "Sainte-Anne-des-Lacs profite dans nos réalisations des extrêmes imperméabilisassent des membranes à froids vulcanisés. On colmate sous tous débords la possibilité vicieuse où l'eau pourrait rebondir en glace. Pour extirper la vapeur et la moiteur empoisonnant les combles, on surchauffe les règles d'entrées d'air par-delà les normatifs avec l'ajouts d'un clouage sans merci pour la longévité de ce palais.",
    "repPart1": "Quand l'hiver mord ou d'odieux rongeurs forestiers percent cette coque de chalet pour fuir les saisons. Que le vent renverse quelques morceaux fatigués: dès les menaces des infiltrations avérées vous sollicitez sans attendre Toiture Jonathan Délisle qui couvre la panade d'une action étanche radicale d'urgence sans vous épuiser en panique matérielle.",
    "repPart2": "Aidé des meilleurs outils de détections et par l'expérience aiguisée de Saint-Anne-des-Lacs, retrouver l'étanchéité bafouée qui coulisse des chevrons est vite acté. Solins de ventilations tordues et jonction d'acier du toit rouillé: avec savoir-faire nous rebâtissons ces mini chantiers isolés, recouvrent harmonieusement les teintes pour recoudre parfaitement votre toit."
  },
  "Sainte-Lucie-des-Laurentides": {
    "posePart1": "Réussir la pose et remplacement d'une toiture dans l'isolement magique de Sainte-Lucie-des-Laurentides c'est bâtir loin des conforts. C'est déployer sur votre autarcique refuge de bois, les gigantesques bardeaux de conception lourdes et l'ingénierie capables d'encaissez le poids incroyable du retard printanier qui plombe toutes les cabines de haute élévations.",
    "posePart2": "L'extraction du vieil enduit désagrégé démontre sans aucune concession les souffrances du platelage en un lieu si dur de Sainte-Lucie. Nous menons une inspection du lit colossalement minutée ; nous extrayons ces planches meurtries qui flanchent sous les tonnages réguliers, le remplaçons d'un OSB de qualité d'ossature pure et de robustesse inouïe.",
    "posePart3": "L'arsenal que Toiture Jonathan Délisle impose face aux assauts d'hiver à Sainte-Lucie débute sous l'imperméabilisation extralarge du pourtour éradiquant drastiquement toutes infiltrations lors des digues thermiques causés du fait du chauffage excessif de grand froid. Enfin une ventilation propulsée, le secret maitre, chassez de jour ces condensations pernicieuses et rend le tout imperméable.",
    "repPart1": "Un accident causé l'orage soudain ou un vieux bris qu'on constate après 3 ans d'absences dans les monts à Sainte-Lucie? Une flaque trône sur votre sol rustique ou endommage les précieux atours: appelez Toiture Jonathan Délisle. Nous agissons en secourisme du bâti dans d'urgentes scellements du trou pour un lendemain garanti à l'abri du fléau humide.",
    "repPart2": "Réparation méticuleuses obligent, nous repistons la fameuse dalles abimés au sommet; ce tuyau maçonné relâchant le mortier corrompu qui draine sur vos murs d'isolants et de la bise d'hiver. En retirant ce désordre local, on implémente sur mesure l'ajustement en solin, un pansement de toiture et un agencement chromatique respectant la forêt vierge du logis."
  },
  "Sainte-Marguerite-du-Lac-Masson": {
    "posePart1": "Le remplacement de l'asphalte près du faste architectural exceptionnel à Sainte-Marguerite-du-Lac-Masson doit représenter la pérennité intemporelle de ces somptueuses habitations. La parure des matériaux laminés de lourdes envergures vient orné vos complexes versant face a l'un des vents lacustre des plus cisaillant du pays, garantissant beauté immuable et longévité structurelle face au front de froids.",
    "posePart2": "Notre professionnalisme commande que le dégarnissement du matériel originel s'effectue en sauvegardant le soin maniaque de l'aménagement domaine laurentien. A nu, la structure est scellé méticuleusement. Aucune assises ne vacille face a nos standard de perfection ; nous solidifions là pour asseoirs l'étanchéités pour toute vie utile.",
    "posePart3": "La stratégie de défense du colisée à Ste-Marguerite est absolue. Notre imperméabilisations est sans reproches, plaquant pellicules hautement auto-adhérentes par-delà chaque géométries tordues, lucarnes immobiles ou noues enchevêtrées qui protègent la richesse du séjour intérieurs. Accouplés par une évacuations mécanique savantes luttant le gel féroce de bord d'eau et ce travail asphalte passe au cap de l'invincibilité régionale.",
    "repPart1": "Si le pire vent des bourrasques centenaires heurte votre demeure laurentienne en arrachants d'innombrables pièces aux abords du majestueux domaine de Ste-Marguerite, Toiture Jonathan Délisle s'engage dans les brefs instant du sinistres. Notre unité bâché l'aire lacéré sans détruire, un rempart au mal hydrique avant les grandes procédures logicielles.",
    "repPart2": "Nous traitons avec finesse chirurgienne ce mal qui contraint vos corniches. D'une infiltrations capricieuses autour des joints de puits de jours abimés ou de crics maçons crevassés, on extirpe la mort apparente et refonde ses parties avec matériaux nobles. Une couverture rétablit imperceptiblement redonne son charmes total aux patrimoines du lac."
  },
  "Sainte-Sophie": {
    "posePart1": "Remplacer sa couverture dans la galopante et immense Sainte-Sophie c'est faire faire des pieds de nés au vieillissements expéditifs et s'encastrer dans l'un des soleils d'été les plus denses. Nos bardeaux architecturaux en plein développements moderne rejette cette caléfaction solaire meurtrière tout en résistant aux glaciations des étendues terres boisées et dures qu'elle présente l'hiver.",
    "posePart2": "À Sainte-Sophie on arrache tout et proprement. Devant de pareils superficies sur ces bungalow d'expansion ruraux on n'opère aucun plâtres temporaires. Chaque contreplaqués OSB de votre charpente exhibe vite son état mental avec l'arrachage, la réintégration aux clous et réparations du planchage qui s'effritait est vital avant l'habillage impérial.",
    "posePart3": "La fortification avec nous c'est les larmiers galvanisé apparier de ces incroyables rouleaux membranes élastomères en bases profondes prévenant la gangrènes de fonte des mois durs, ancré. Le balais de bardeaux posé selon le livre face aux orages d'aout, s'agence pour l'optimisation cruciales à Sainte-Sophie: La ventilation repoussé qui sort ce miasme chaleureux en été pour que cette toiture vive ces jours glorieux de ses garanties complètes.",
    "repPart1": "L'inattendu vient en rafales sans sommation; une tôle brisée et un déluges ruine l'espoir au plafond. Sans la procrastination à l'œuvre Toiture Jonathan Délisle intervient du bout des territoires vers vous à St-Sophie; Calfeutrants sans tarder de grosses pellicules armaturés sur la blessure de votre demeure afin qu'elle survive le mal.",
    "repPart2": "Lutter corps pour arrachements asphalte, ou scelleur de base de plomberies arrachés est notre pain quotidien a Ste-Sophie. Le diagnostic, loin de la supposition hasardeuse on dépiaute une modeste aire local et reconstituer d'acier franc et asphalte coordonnés tout bris à son intégrité pure, la ou l'eau récidivante sera neutralisé a jamais."
  },
  "Val-David": {
    "posePart1": "S'attarder aux remplacements délicats de ces charmants logis et écoconstructions de Val-David est pour un couvreur un défi artisan exceptionnel. Les formes et chaleurs humaines du village ne méritent point l'ordinarité matérielle, d'où nos recommandations d'asphalte architectural lourd qui absorbe les rigueurs et moule à l'effigie créatrices le cœur d'une protection solide.",
    "posePart2": "Le déploiement des effectifs à Val-David prends sens par l'arrachement patient, avec soin et déférents de vos atours sauvages extérieurs. Lorsqu'il nous est donné de témoigner des vieux bardeaux désagrégés, on déniche du vieux lits d'assise tordu: nos charpentiers la redresse vigoureusement la nivelant et lui procurant un fondement robuste qui rassurera des âges l'architecture valdavidoise.",
    "posePart3": "La géographie enclavé dans val David sature l'air d'humidité de finissions. Cette membrane lourde au socles, des pourtours et jonctions complexes vient endigués toute rémanence au retour d'eau qui cherche la fuite lors de ses froids de mars si spécifiques. C'est ensuite le clouage méticuleux puis le rafraichissement totale des ventilations de cette espace d'air, garantissant un toit étanche qui expire.",
    "repPart1": "Ces bourrasques redoutable aux corniches montantes de Val-David sur vos résidences causent parfois un affaissement structurel impromptus au matériaux usés de ce logis. Lorsque que la précipitation fâcheuse gagne, Toiture Jonathan Délisle pare l'offensives sans tracas : On déploient armure impénétrable prévenante à l'assassin de confort pour le jour présent.",
    "repPart2": "Le toit ancestral crie famine ; cette lucarne de votre atelier coule goute à goute ! Nous agissons à Val-David comme traqueurs : dépouillant l'inutile ou la structure bafouée pour réadapter cet ornement a la couverture saine . Repositionnant l'agencement couleur en bardeau on en fait notre réparation furtive qui résilie cette faille a l'eau en parfaite invisibilités décoratif."
  },
  "Val-des-Lacs": {
    "posePart1": "Ouvroir à cette nordicité lointaine laurentienne pour Val-des-Lacs un remplacement d'asphalte asseau a l'ingénierie et l'armement du bardeau haut grade absolu. Pour survivre, ces autarcies sauvages éloignées ne doivent se rabattre qu'au plus denses et fixées revêtement qui contrestera le souffle froid des corridors et l'amassements cyclopéens d'hiver aux lacs en hautes collines.",
    "posePart2": "C'est devant une base a vif sous la vielle chape retirer qu'évolue la science de protection absolue de Toiture Jonathan Délisle. À Val-des-Lacs on ne cache rien : si cette charpente sous OSB se tord sous le courroux d'hivers successives, nous scions, on remodèle a neuf et visse de plein pied les surfaces pour redonner au sommet sa splendeur invulnérable et porteuse pour 30 ans.",
    "posePart3": "Le bouclier final a Val-des-Lacs implique une laide démesurément étendues d'autocollantes membranes caoutchouteuse dans tous escarpements au bas du toit de l'immobile résidence. Empéchant ce glacier rampant de pourrir les plafonds cathédrale. A l'assaut la ventilation modernisée extirpe des hauts tout condensat chaleureux laissant un froid sec du combles: la toiture impériale est ici vivantes.",
    "repPart1": "Isolé loin derrière , vous remarquez une béance arrachée et l'humidité dégouline sur la table d'orme? Ne laissez cet ennemi faire l'emprise, nos équipe d'intervention urgentes part vers Val-des -Lacs combler la plaie du vent, refermant cette boite a malheurs à grands coup calfeutrent provisoire en toute étanchéités de l'acier fort.",
    "repPart2": "Une faille à la chaleur du foyer: une cheminées centenaires usées a ce ferblants. Ou une percés par des écureuils farouches abimant l'exausteurs: ici la réparation chirurgical se met en places a Val-des-Lacs. Avec finesses l'endroit affligé est retirer d'un bout et reconstruit avec nos éléments d'alliages et d'asphaltes fusionnels sans tares apparente et garantie solide face au déluge prochain."
  },
  "Val-Morin": {
    "posePart1": "Réinventer la toiture à l'approche la douceur historique et bord de cette impériales rivière du Nord dans Val-Morin est un art qui respect la poésie des chalets. La force incroyable de notre couverture par la méthode et d'ingénierie se traduit face avec cet incroyable brouillard perpétuelle du petit matin qui grugés les assises du matériels de nos sommets riverains.",
    "posePart2": "Dénudé, l'anciennes chape cède son espace méticuleusement dégagés, protégeant vos havres de paix a de Val-morin sans casse ou rebuts traînants. C'est l'examen franc de votre platelages jadis vicié : nous extirpons tous supports malhabiles ou courbés du fardeau nordique passés pour remanier l'intégrales structure d'accroches du bardeau.",
    "posePart3": "C'est la guerre au gel marin a Val-Morin. Par application immenses de nos rubans étanches large de vulcanisées le boucliers se ferment devant la glace grignoteuse. Nos charpentes sont cloue à point sans fentes et la ventilations du comble corrigé repousse avec violences à l'extérieur ce miasme humide fatale qu'est l'érosion caché pour revivre une grande durée en totale sécurités de protection.",
    "repPart1": "Ce vent fracassant qui balais le fond de cuve et hop le déchirements et la toles a nues! Une gouttes vient ternir la beauté val morinoise? L'appel à  Toiture Jonathan Délisle déploie en d'infimes instant l'ordre paramédicale rapide : un pansement massif pare intempéries bloquant l'offensives dans votre quiétude intérieurs.",
    "repPart2": "Que la cheminés se fende avec âge , les vieux flashings écartelé le longs des pures versants ou ce bris fâcheux en plein tuiles de toitures de Val-Morin : c'est alors qu'opèrent nos savantes mains charpentière. Tranchants ce malade en carrés nous re-infiltrons l'isolations et tuiles raccordées,  sans différence de teintes par une belle réparations discrètement redoutables en son point névralgique."
  },
  "Wentworth-Nord": {
    "posePart1": "A ce seuils ultime d'éloignement  pour ce coin reculés des bois a Wentworth-Nord, les logis  veulent s'allier des forteresses. L'asphalte architecturale épaissie a un degré de renfort invincibilité  et armé en conséquence, se dote de nos meilleurs armes en pose pure repoussant l'inexorables agression hivernales  seules dont souffrent nos immobiles demeurent.",
    "posePart2": "Notre profession exige un dépouillement à l'os , sans gants de velours vis-à-vis du déchets retirés, d'exposé sans cachettes ses panneaux intérieurs souffrants a Wentworth-nord. L'aération originelle bafouée est souvent cause de mort précoce des lits intérieurs de soutiens où cette déroute charpentières se voit solidifiés a perfection et raccordé d'OSB avant l'impositions des nouveaux jours asphalte.",
    "posePart3": "La sécurisation des chalet isolés impliques au confins de colline l'abrupte déploiements de membrane autocollants larmier colossales devant des précipitations faramineuse sur ses corniches de froid. Le grand tout arrimés est fixés par fixations double  sur les tuiles de grades ultimes contre le bourrasque et cette ventilation aérées a profusions assure d'éliminés toutes chances moiteur des pièces du bois du reste de ce logis. Le pur joyaux invincible.",
    "repPart1": "L'outrage subits a cet immenses refuge  par une rafale fendant une toiture laisse sans voix . Quand sa fuit a  Wentworth-nord ont appelles nos urgences. L'écuelles n'y fera pas : on deploits  cette couverture solide d'arrêt instantané de Toitures Délisle et met fin à tout espoir d'eaux d'abimer votre sanctuaire dans  l'isolement .",
    "repPart2": "De collet rongés sur la bases du renvoies, de solins arraché par cette glaces rampante où les fissures indésirables ouvrant sur rien: à Wentworth-Nord notre corps professionnel exècre  la fuite à l'eau de charpente. Le travail soigné c'est d'aller excaver ce mal en son points fixe, posé notre d'acier inoxydable de rétentions par de robustes asphalte  colorisés afin refermé un travail garanti à vie utile."
  }
};
