export const SERVICES_BATCH_2: Record<string, any> = {
  "Mont-Tremblant": {
    "posePart1": "Au Mont-Tremblant, l'installation de toitures est élevée au rang d'art pour préserver le prestige des grands domaines et dompter le froid sibérien. Fini les matériaux standards. Nous n'utilisons que des bardeaux architecturaux de la plus haute caste, parés contre les pires turbulences hivernales du plus haut sommet habité du coin.",
    "posePart2": "Le déshabillage de votre ancienne couverture à Mont-Tremblant se fait avec une vigilance totale vis-à-vis du terrain paysager. Une fois le pontage à découvert, nos charpentiers consolident sans faille la charpente, remédiant à tout dommage causé par le lourd fardeau du verglas ou de la glace des dernières années.",
    "posePart3": "La pose des bardeaux sur les immenses propriétés de Tremblant s'accompagne d'un système de membranes autocollantes extralarges, formant un véritable coffre-fort autour des immenses lucarnes et des vallées. La circulation d'air (ventilation par corniche et pignon) est recalibrée pour empêcher l'air chauffé de stagner dans l'entretoit, annihilant la formation insidieuse de glace.",
    "repPart1": "Une tempête mémorable au Mont-Tremblant s'est acharnée sur votre toiture ? Si l'évitement des précipitations a échoué et que l'eau menace la splendeur de l'endroit, notre intervention d'urgence entre en jeu. Nous effectuons l'arrêt immédiat des fluides pour préserver vos plafonds en cèdre et gypse délicats.",
    "repPart2": "La réparation toiture à Tremblant ne s'improvise pas; notre équipe chirurgicale démonte avec soin le bardeau arraché ou le vieux métal, dénichant le vide invisible d'où la fuite origine. Puis, l'étanchéité est reconstituée selon les standards commerciaux grand luxe, s'intégrant parfaitement pour honorer la dignité de votre architecture."
  },
  "Morin-Heights": {
    "posePart1": "Le projet de pose de bardeaux d'asphalte à Morin-Heights honore les nombreuses résidences centenaires et écologiques tapies sous la dense canopée. Les dépôts organiques et le faible rayonnement solaire exigent d'épais bardeaux traités contre l'envahissement des mousses, préservant la santé et l'allure rustique des maisons forestières.",
    "posePart2": "Arracher le vieux matériel s'accomplit chez nous méticuleusement, en sécurisant la biodiversité environnante de votre propriété de Morin-Heights. L'inspection des pontages (souvent en planches embouvetées à l'ancienne) nous guidera et nous ajustons nos attaches pour revigorer cette structure fatiguée avant la pose.",
    "posePart3": "L'ingénierie prend le relais avec la membrane d'assise. Pour parer la pluie diluvienne qui s'écrase des grands arbres, la protection est doublée au périmètre. Morin-Heights connaissant des cycles humides importants, des prises d'air surdimensionnées aux avant-toits et des sorties de haut niveau garderont la toiture en synergie, au sec des décennies durant.",
    "repPart1": "L'incident est vite arrivé à Morin-Heights: la fameuse chute dominicale de branche brisant le bardeau ou l'effondrement causé par l'amas de neige glacée affaissant le balcon supérieur. Nos solutions d'urgence mettent votre nid familial hors du danger des intempéries rapidement, sans attente.",
    "repPart2": "Une tuile arrachée sur un toit pentu ou un évent de plomberie déchaussé dans la forêt peut s'infiltrer sournoisement. Notre service de réparation à Morin-Heights creuse derrière la pathologie pour y faire une reprise impeccable. Raccordement et pose des nouveaux bardeaux jumeaux assurent l'effacement total du sinistre."
  },
  "Piedmont": {
    "posePart1": "Les remplacements de toiture en asphalte à Piedmont ont cette spécificité d'être souvent juchés sur des caps défiants la gravité. Les résidences de prestiges ou les propriétés d'architecte qui font l'admiration depuis la vallée réclament une couverture lourde, visuellement éclatante, et ancrée pour affronter les rafales thermiques inouïes des falaises.",
    "posePart2": "La pureté des assises fait l'authenticité de la solidité à Piedmont. Le démontage révèle bien des surprises avec les grands froids subis, particulièrement la délamination des panneaux OSB de votre bois de soutien. Nous restaurons ces panneaux sur-le-champ pour former le litement inébranlable apte à accueillir notre garantie.",
    "posePart3": "C'est la guerre contre l'eau de fontes rapides sur la crête ensoleillée de Piedmont: nos maîtres couvreurs appliquent sans lésiner l'armure qu'est la membrane caoutchouteuse par-dessus tous les corniches, angles et pignons exposés. Les bardeaux se clouent fermement selon le modèle de haute vélocité de vent et l'air d'entretoit circule par nos faîtières modernisées.",
    "repPart1": "Un lourd pan de glace descend du versant à Piedmont et emporte la gouttière et l'avant-toit. Les intempéries frappent brutalement la maison de la crête. Un appel à Toiture Jonathan Délisle initie le déploiement express d'une toile isolante, parant aux infiltrations de l'orage jusqu'à l'évaluation fine.",
    "repPart2": "Un couvreur à Piedmont sait qu'une fuite peut courir sur un fil de bois pendant dix mètres. De la réparation délicate des solins longeant l'impressionnante cheminée du salon, jusqu'au recollement d'une façade d'évent arrachée, les bris sont diagnostiqués et refermés définitivement sans aucun compromis sécuritaire ou esthétique."
  },
  "Prévost": {
    "posePart1": "Prévost et sa vallée connaissent les remplacements de toiture constants, dus en grande majorité au cocktail d'humidité et d'étranglements des vents nordiques. Que votre maison soit un classique de la rue Principale ou à proximité des falaises, le bardeau architectural épais y excelle par son adhésion thermique qui résiste à ces tempêtes de canyon.",
    "posePart2": "Au début des travaux sur votre toit de Prévost, tout le vieil asphalte est acheminé scrupuleusement vers les bennes, sans briser vos platebandes. Le diagnostic du panneau d'ancrage en bois est l'étape crève-cœur mais vitale: l'absence d'ondulation dans le toit prouve le succès de l'assise, ce que nous garantissons avec des charpentiers minutieux.",
    "posePart3": "Sur les pentes plongeantes des toits cathédrale ou sur les grands toits plats voisins, notre tactique à Prévost est simple : membranes élastomères dédoublées à la corniche, fixations galvanisées redondantes et aérateurs redessinant la circulation des combles. Plus de bois humide en janvier, la nouvelle toiture vit et respire !",
    "repPart1": "La force d'un orage localisé dans la vallée de Prévost peut parfois enrouler de vieilles tuiles 3 pattes. Dès le spectacle désolant des bardeaux dénudés, vous appelez Toiture Jonathan Délisle, et l'équipe calfeutre la plaie ouverte dans un effort d'urgence protégeant immédiatement votre intérieur, sans question.",
    "repPart2": "L'entreprise identifie infailliblement la petite gouttière d'eau vicieuse : un calfeutrage émietté du faîte du toit, un pignon où la tôle est écartelée par le gel. En effectuant la réparation à Prévost, nos techniciens délogent le matériau caduc et tissent de nouvelles bardeaux coordonnés, pour qu'il ne paraisse même pas que votre toit eut pépins."
  },
  "Saint-Adolphe-d'Howard": {
    "posePart1": "Faire de la toiture à Saint-Adolphe-d'Howard c'est composer l'ultime défense contre l'hiver laurentien en haute élévation. L'accumulation écrasante de neiges réclame l'utilisation de nos bardeaux laminés de haute performance, capables de ne pas fissurer aux pires froids ni de courber sous le poids de la bordée printanière.",
    "posePart2": "Les propriétés de Saint-Adolphe se méritent les fondations parfaites : en décortiquant les couches successives passées, vient le clouage du bois de substitution pour ériger un platelage sain de moisissures. Le cœur du bois bien ventilé est la base pour soutenir l'isolation de votre maison perchée ou de votre retraite isolée.",
    "posePart3": "Face aux barrages de glaciers mortels de février qui sont légion, nous imposons l'épaisseur des bandes autocollantes imperméable de Saint-Adolphe bien au-delà de la ligne chauffante de la demeure. Scellant chaque brèche de tuyauteries ou puits de lumière, avec notre aération maximisant l'expulsion chaleureuse, votre nouvelle couronne asphalte dompte les géants froids.",
    "repPart1": "Impossible pour vous, isolé, d'affronter une digue de glace ayant réussi à fendre l'asphalte et inonder le plancher de bois franc. Notre flotte de Saint-Adolphe-d'Howard procède à la gestion express des fuites, stoppant dans son élan toute ruineuse dégradation hydraulique causée spontanément par dame nature.",
    "repPart2": "Chaque réparation sur passe par l'ouverture ciblée: l'ablation avec finesse de l'asphalte soulevé par le vent ou miné par la glace. À l'image d'artisans, nos maîtres couvrent l'ouverture et installent fixations, membranes à froid et tuiles colorées au diapason. Votre retraite d'ici garde sa grandeur, le dommage effacé à jamais."
  },
  "Saint-Colomban": {
    "posePart1": "L'expansion effrénée de Saint-Colomban donne droit à d'immenses réalisations en remplacement de bardeaux. Des grandes toitures complexes sur maisons aux pignons nombreux commandent l'élégance et la résistance du bardeau architectural que Toiture Jonathan Délisle emploie en permanence, pour asseoir la réputation de votre solide quartier.",
    "posePart2": "Les constructions en périphérie à Saint-Colomban sont arrachées et inspectées. Notre expertise décèle sur ces grandes surfaces de toitures la moisissure hâtive liée très souvent à une piètre ventilation d'origine. Les bases purifiées et les panneaux arrimés solidement assurent une rectitude absolue lors des travaux d'envergures de nos spécialistes.",
    "posePart3": "La stratégie est la fortification. L'étendue de la propriété aux toits multiples nécessite l'installation méticuleuse des solins d'acier prépeint discrets et la générosité des barrières étanches autocollantes dans les noues prolongées de Saint-Colomban. Et, pour expirer l'accumulation d'air humide colossale sous ce grand plafond, nous fixons les systèmes d'exhaustions à la performance calibrée selon les aires cubiques exactes.",
    "repPart1": "Un front froid accompagné de coups de tonnerre peut disjoindre une gouttière et le fascia de Saint-Colomban en pleine nuit. Le résultat: l'eau qui s'invite sans prévenir dans vos plafonniers. Notre unité est celle qui bloque et sécurise l'eau à l'extérieur par des bâches ancrées ou par scellement lourd instantané, sans faire la sieste.",
    "repPart2": "Avec des toits à pentes variées, les infiltrations découlent fréquemment d'un joint d'étanchéité mortifère de lucarne mal bâtie. Nos docteurs en réparation se déploient à Saint-Colomban, rectifiant solins, arrachant sous-couches douteuses et refaisant ces failles de zéro; fusionnant le nouveau pan invisiblement au restant de la toiture unilatérale."
  },
  "Saint-Faustin-Lac-Carré": {
    "posePart1": "L'héritage d'intervention à Saint-Faustin-Lac-Carré, avec ses magnifiques vallons, dicte de remplacer les vieux revêtements désuets par de robustes gammes asphalte de calibre architectural. Oubliez les fins modèles pliant sous l'ouragan, nous n'armons ce flanc de montagnes qu'avec ce qu'il a de plus digne pour supporter la pluviosité élevée de la région.",
    "posePart2": "Retrancher la toiture usée au complet permet d'ausculter l'état psychologique et physique de la grande charpente ancienne de Saint-Faustin. Ce travail ingrat est pour tant le plus important. Tout pontage désagrégé dû aux gels des ans est expurgé pour laisser place à la résilience infaillible d'un lit massif de bois parfait.",
    "posePart3": "Il faut clouer massivement à Saint-Faustin pour parer aux vents ascendants capricieux des lacs Carré. La ceinture thermale d'étanchéité, une vaste membrane caoutchouc d'hiver, empiète généreusement sur votre toit pour sceller la sécurité du logis face au gel dévastateur. Enfin, la respiration salvatrice de votre espace grenier fait partie intégrante de la science mise en place par nos soins.",
    "repPart1": "Au retour de l'hiver, le cauchemar de voir un faîte dégarni s'ouvrant aux pluies battantes printanières de Saint-Faustin est un fardeau qu'aucun propriétaire ne veut vivre. Une simple prise de contact lance l'intervention d'urgence : barricader la faille à l'abri jusqu'au correctif, garantissant un logis préservé du mal.",
    "repPart2": "Une réparation en ces contrées n'est réussie que par l'identification parfaite de l'origine de fuite (un évent lâche, un cap ou revêtement craquelé par une tempête de grêle). Les experts de Toiture Jonathan Délisle excavent délicatement cette pathologie pour replacer sur-mesure la couverture de protection durable."
  },
  "Saint-Hippolyte": {
    "posePart1": "Un projet à Saint-Hippolyte se définit par un environnement extrêmement marin et brumeux pour cause des myriades d'eaux douces. Égayer et durcir vos chalets ou luxueuses demeures avec l'asphalte architecturale de qualité biocide, qui contrarie l'enracinement des lichens destructeurs, c'est ce qui allonge dramatiquement la belle finition des œuvres que nous complétons ici.",
    "posePart2": "La discipline du charpentier nous incombe lors de l'arrachage. Nos effectifs survolent la pente au lac à Saint-Hippolyte en garantissant nullité de rebuts résiduels, dévêtant le toit. Nous purifions le squelette de la maison: enlevant clous, tôle rouillée, et réparant le contreplaqué endolori par l'air stagnant, un incontournable absolu pour valider l'assise.",
    "posePart3": "Toutes ces maisons encastrées subissant la forte brise d'en haut profitent d'un soin particulier avec le système résilient aux traînées d'eau que nous construisons. Multipliant l'attache des bardeaux et appliquant le linceul protecteur en double aux noues et faîtes compliqués de Saint-Hippolyte, nos travaux comportent la modélisation à neufs d'interstices bien ventilés, ce qui arrête le massacre par condensation.",
    "repPart1": "Une vilaine trombe de vent d'été au bord de votre lac arrache-t-elle cet élément métallique et l'asphalte centré avec? Devant le vide d'où pénètre les orages, les équipes rapides de Saint-Hippolyte posent l'armure provisoire mais indestructible. On bloque de suite la tempête, sans perte de meubles intérieurs.",
    "repPart2": "Une réparation de qualité implique de retracer le gisement exact d'où l'eau se fraie une descente. Soit la maçonnerie du foyer mal colmatée, ou ces jonctions d'extensions où la flotte trouve faille. Réparer la couverture à Saint-Hippolyte à ce niveau, ce n'est pas le goudron, mais la confection d'un ouvrage artisanal réintégrant la beauté initiale sur la zone affectée."
  },
  "Saint-Jérôme": {
    "posePart1": "Capitale régionale oblige, le remplacement intensif de bardeaux à Saint-Jérôme est le cœur des interventions quotidiennes sur tous ces styles de domiciles juxtaposés aux quartiers des affaires. Contrer le réchauffement des îles de chaleur urbaines exige l'asphalte architectural dense et modernisé, offrant de majestueux coloris ainsi qu'un repoussé naturel contre le pourrissement chaleureux d'été.",
    "posePart2": "Toiture Jonathan Délisle nettoie chaque vestige de couverture avec une courtoisie citadine imbattable; chaque bardeaux de la banlieue retourne à un bac sécurisé. Et la révélation qu'apporte le pontage à un couvreur détermine la marche : si vos habitations historiques ou bungalows de St-Jérôme recèlent des plaies du bois sous-jacent, nos professionnels rectifient pour une garantie immuable à 100%.",
    "posePart3": "Cimenter le futur du logis à Saint-Jérôme, cela passe en établissant la barrière anti-infiltrations massive autour de vos bordures et puits de lumière à proximité du trafic. Parachevant l'installation, nous mettons notre grand orgueil technique sur pied: un maillage complet de trappes d'entrée à soffites jusqu'aux cheminées aéromécaniques (maximum). Résultat, fin du calvaire de cuisson pour vous et pour le bardeau.",
    "repPart1": "Le déluge accablant la métropole laurentienne est redoutable. Faille à la toiture ? Flaque d'eau sur vos divans à Saint-Jérôme ? Nos équipes de secouristes déploient bâches lourdes ancrées, pour faire de la gestion de sinistre temporaire la plus étanche de votre nuit. Rien n'est plus frustrant, donc nous faisons vite.",
    "repPart2": "Un clou exposé et rouillé, le fascia gondolé libérant la pluie ou l'érosion aux abords des ventilateurs par un nid de rongeurs; la toiture à Saint-Jérôme répare méticuleusement l'entaille. Les techniques sont chirurgicales : arrachage, inspection des isolants mouillés, re-structure, coulis vulcanisant et des nouvelles tuiles fondues avec vos palettes de couleurs existantes."
  },
  "Saint-Sauveur": {
    "posePart1": "Trônant au cœur de la Mecque vacancière des Laurentides, agir en tant que couvreur à Saint-Sauveur requiert d'offrir des remplacements exceptionnels et durables au niveau du prestige de la vallée. Nous déployons de l'asphalte laminé dont les granules ont été façonnées pour un panachage gracieux et une résilience spectaculaire contre l'orographie complexe qui balaie la vallée du vent et de la neige sans relâche.",
    "posePart2": "Sous ce visuel classieux, le travail sans fard prend forme chez Toiture Jonathan Délisle : chaque chantier à Saint-Sauveur est un dépouillement en douceur protégeant votre élégance florale. La préparation des feuilles de bois qui se dessinent demande notre minutie experte; la fondation de votre chalet doit être un monolithe inaltérable et sec avant l'étape de recouvrement.",
    "posePart3": "La sécurisation s'opère sur ces pentes avec clouage extrême et d'abondantes écharpes de membranes élastomères auto-adhérentes pour empêcher ces formidables digues de glaces (dues aux chaleurs du toit) de fracasser votre vie intérieure. Saint-Sauveur est particulièrement rude en gel et l'aération calibrée sur faîtière que nous implémentons, est là votre assurance longévité par excellence.",
    "repPart1": "Surpris par les foudres hivernales, la rafale subite arrachant lucarne et corniches laisse vos investissements intérieurs grand ouverts dans la vallée. En ce moment dramatique à Saint-Sauveur, de puissantes armures temporaires colmatent les voies en urgence pour sauvegarder sans pitié toute infiltration destructrice à travers votre gypse de luxe.",
    "repPart2": "Diagnostiquer ce grand mystère que sont les pénétrations d'eau à pente forte: voila notre mandat de réparation à Saint-Sauveur. C'est en expert évaluant ce pignon défraichit ou ce puits de jour lâche que l'équipe opère chirurgicalement le bardeau existant pour y joindre avec brio du nouvel asphalte et solin impénétrable d'usine."
  }
};
