export const SERVICES_BATCH_4: Record<string, any> = {
  "Amherst": {
    "inspPart1": "L'inspection de toiture à Amherst est une pratique de prévention essentielle, surtout compte tenu du couvert forestier dense qui encercle la municipalité. Une vérification automnale garantit le nettoyage de vos gouttières pleines d'aiguilles de pins et prépare votre demeure au gel à venir, tandis qu'une inspection printanière permet de déceler tout dommage causé par le lourd fardeau de la neige hivernale.",
    "inspPart2": "En tant qu'entrepreneur en toiture à Amherst, nous prônons une intégrité totale dans nos diagnostics physiques. Pour une propriété choyée depuis des décennies ou lors d'une transaction immobilière locale, nous relevons toute vulnérabilité afin de vous protéger contre des réparations inattendues dispendieuses.",
    "inspPart3": "Lors de notre auscultation à Amherst, nous analysons chaque composante: de la perte de granules protectrices jusqu'aux solins d'étanchéité de cheminée pouvant être craquelés. L'évaluation de l'entretoit permet d'assurer qu'aucune moisissure causée par le microclimat forestier humide n'affecte la charpente, assurant ainsi la sécurité complète de votre investissement.",
    "deneigPart1": "Les hivers à Amherst imposent des précipitations de neige prodigieuses. Un service de déneigement de toiture Laurentides y est crucial car la neige durcie par les vents froids constitue une surcharge pondérale très dangereuse menaçant directement l'intégrité de vos fermes de toit.",
    "deneigPart2": "Au-delà du poids brut, les redoux passagers créent des barrages de glace redoutables aux rebords de toits. La glace emprisonne l'eau fondante, qui n'ayant d'autre échappatoire, remonte sous l'asphalte et s'infiltre massivement dans vos plafonds intérieurs.",
    "deneigPart3": "Bannissez les pelles métalliques et les manœuvres risquées. Notre équipe certifiée opère le déneigement de votre chalet à Amherst en utilisant des harnais sécuritaires et des grattoirs en polymère doux pour ne jamais entailler vos bardeaux, conservant intactes les garanties de fabrication.",
    "pourquoiIntro": "Pour la protection des chalets à Amherst, Toiture Jonathan Délisle Inc est incomparable. Outre le simple devis bas de gamme de compétiteurs, c'est notre science approfondie du climat forestier et des spécificités techniques du milieu qui font de nous la véritable référence de la couverture dans les Laurentides."
  },
  "Arundel": {
    "inspPart1": "La vallée agricole d'Arundel est reconnue pour ses bâtiments centenaires et ses bourrasques de vent régulières. Une inspection de toiture en amont permet de détecter des failles invisibles laissées par de récentes tempêtes, et d'entrer dans l'hiver sans craindre le pire.",
    "inspPart2": "Que vous soyez l'héritier d'une vieille grange revampée ou d'une charmante ancestrale à Arundel, notre inspection franche et honnête devient un formidable outil d'investissement et de maintien au sec pour votre famille.",
    "inspPart3": "Nos couvreurs vérifient ardemment les moindres faiblesses: gondolement de bardeaux liés aux rafales, solidité des gouttières ou défaillance du faîte d'aération. Ce compte-rendu transparent vous donne un panorama absolu de l'état de votre enveloppe supérieure, sans incitation aux dépenses superflues.",
    "deneigPart1": "Dans les grandes plaines d'Arundel, l'accumulation de frimas devient vite préoccupante. Le déneigement de toiture n'est pas une fantaisie, mais l'unique garantie d'empêcher les impressionnantes accumulations poussées par le vent de faire fléchir la structure des vieux toits.",
    "deneigPart2": "Les amas de neige se transforment trop vite en digues glaciaires asphyxiant les rebords. Si ce bloc ne permet plus l'égouttement vers les fascias, c'est votre isolation intérieure qui subira une infiltration foudroyante.",
    "deneigPart3": "Les travaux en hauteur l'hiver sont l'affaire de professionnels à Arundel. Notre méthode de dégarnissage, qui respecte une sous-couche neigeuse pour préserver la granulosité de vos bardeaux, est la façon la plus sereine de traverser l'hiver à l'abri du fléau asymétrique du poids de la glace.",
    "pourquoiIntro": "Le climat de la vallée d'Arundel exige des fixations qui tiennent tête aux vents et des solins impénétrables. Choisir Jonathan Délisle Inc, c'est investir l'esprit tranquille chez un partenaire minutieux, reconnu bien au-delà de la stricte considération de la facture."
  },
  "Bellefeuille": {
    "inspPart1": "Dans les quartiers familiaux en pleine expansion à Bellefeuille, l'inspection de toiture s'avère la clé pour la quiétude des parents. Inspecter avant l'arrivée du gel et suite aux gros épisodes de verglas permet d'allonger la durée de vie des bardeaux apposés en nombre parsemés d'arbres matures.",
    "inspPart2": "Spécialistes de la toiture sur la plaine de Bellefeuille, nous offrons une inspection visuelle inestimable aux futurs acquéreurs et résidents pour déjouer toute vice caché et optimiser le soin immobilier.",
    "inspPart3": "Lors de notre évaluation complète, chaque intersection critique entre le toit principal, les lucarnes architecturales, et les cheminées est scrutée. S'ajoutent une vérification de la justesse de l'isolation du comble, l'assurance de clous intacts, le tout présenté en toute honnêteté dans notre rapport sans ambiguité.",
    "deneigPart1": "Sans la protection dense des montagnes, les toits de Bellefeuille subissent le poids mort des importantes tombées neigeuses gorgées d'eau. Notre stratégie préventive de déneigement protège votre foyer contre les énormes pressions que subit la charpentre en fléchissant.",
    "deneigPart2": "C'est l'épisode gel-dégel aux avant-toits de ces nombreux bungalows qui crée le péril : des murs de glace repoussant sans cesse le liquide stagnant à travers de la fibre d'asphalte vers vos murs de chambres ou de salons.",
    "deneigPart3": "Évitez la blessure ou l'annulation de vos garanties constructeurs en essayant d'abattre ces amoncellements gelés vous-même. Confiez l'opération à notre équipe experte à Bellefeuille, qui déblaie en toute conformité et respect absolu de votre couverture avec pelle en plastique de spécialité.",
    "pourquoiIntro": "À Bellefeuille, l'esthétique compte tout autant que l'étanchéité. Nous dominons ces standards par l'apposition luxueuse de produits de marques mondiales, tout en maintenant les fondations du service centré sur l'être humain propre à notre réputation implacable."
  },
  "Estérel": {
     "inspPart1": "Dans les majestueux domaines boisés d'Estérel, la prévention est essentielle au maintien de la beauté noble. La proximité des lacs grugés de vents glacials force l'inspection de votre toiture au printemps, confirmant qu'aucune infiltration sournoise ne vienne entailler vos formidables finitions à aire ouverte.",
    "inspPart2": "Les propriétés luxueuses doivent traverser le temps, et un maître-couvreur comme nous agissant sur le territoire d'Estérel y apporte une inspection méthodique pour sécuriser le propriétaire méticuleux devant tout investissement surprise ou vice structurel latent.",
    "inspPart3": "Notre processus analyse intensément chaque détail architectural ; tourelles, larmiers massifs et complexes de vos faîtes. L'examen des moindres dégradations du bitume ou du calfeutrant solaire donne suite avec élégance, sous forme d'une appréciation juste, neutre et honnête.",
    "deneigPart1": "Bien que l'esthétique cathédrale prévale à Estérel, le souffle de la montagne et des conifères s'avère un piège hivernal lourd à manœuvrer. Nos techniques de déneigement en urgence assurent la souplesse inestimable à vos lourdes charpentes face aux blizzards continus du Nord.",
    "deneigPart2": "C'est devant la constitution d'un front de glace bloquant l'égout aux rebords du toit que les infiltrations naissent. Plus l'eau stagne sur vos toits-verts ou mansardes d'Estérel, plus elle cherche avec avidité la chaleur vers l'intérieur.",
    "deneigPart3": "Ne heurtez point l'architecture fine ou les bardeaux premium avec le fer improvisé. Un harnachement sans la moindre égratignures et la suppression en finesse par des artisans est l'offre luxueuse de toiture Jonathan Délisle a votre domaine de prestige en bordure d'Estérel.",
    "pourquoiIntro": "Un environnement de domaine somptueux comme à Estérel n'accepte aucun manque aux finitions. Nos engagements vers les membranes les plus onéreuses et la protection soignée de l'aménagement paysagiste répond exactement aux impératifs d'une élite désirant d'exceptions."
  },
   "Lac-Supérieur": {
     "inspPart1": "La météo crue du nord à Lac-Supérieur oblige la plus pragmatique des inspections de toiture : sans filet ni indulgence face aux vents dominants d'altitudes, un bilan serré des solins avant l'assaut hivernale vous éloigne de conséquences hydrauliques cataclysmiques.",
    "inspPart2": "Que l'on examine ce gite locatif d'hiver nouvellement acquis ou votre résidence d'attachement infini devant les cimes, l'examen transparent et intègre fournit le plein contrôle à tous propriétaires prévoyants, éloignant grandement la ruine due a la paresse.",
    "inspPart3": "On monte à Lac-Supérieur vérifier les microfissures inhérente aux bardeaux très froids, le maintien absolu de votre ferblanterie devant le gel à moins vingt degrés, pour aboutir par l'auscultation d'un entretoit sain, parfaitement ventilé afin d'éviter d'alimenter cette moisissure du combles par de l'isolement sans souffle.",
    "deneigPart1": "La haute montagne de Lac-Supérieur livre sans gêne les plus colossales quantités de neige à vos toits. Pour empêcher ces amas records d'excéder les limites physiques de charge en pesée des chevrons, le déneigement y est devenu obligatoire.",
    "deneigPart2": "Rien de plus fatal en élévation alpines que le barrage de glaçon naissant d'un puissant redoux ou de la seule perte thermique causée du foyer, ces barrières de plusieurs pouces obligent l'eau à se frayer des tunnels dévastateurs jusqu'à vos pièces de nuits.",
    "deneigPart3": "La sécurisation vertigineuse d'intervention à Lac-Supérieur réclame que vous fassiez recours à l'expertise reconnue de Jonathan Délisle. Nos professionnels sur cordes d'assurance laissent le revêtement sain et sauf car aucuns frottements ne se rend avec brutalité sur vos granules bitumés protectrices.",
    "pourquoiIntro": "Sur les pentes extrêmes de Lac-Supérieur, nos clients s'approprient Toiture Jonathan Délisle Inc non pas pour les aubaines ridicules du marché, mais pour le déploiement pur du matériel et systèmes mécaniques à très hautes densités capables d'opposer dignement dame nature dans ce qu'elle a de dantesques."
  },
  "Lantier": {
    "inspPart1": "Profondément localisé en contexte de forêt dense, la toiture d'un pavillon ou gite à Lantier subit d'immenses vagues végétales organiques. S'en tenir à une inspection préventive sauve littéralement les bardeaux de la moiteur ombragée et prolonge de dix ans votre intégrité.",
    "inspPart2": "Les propriétés centenaires qui font foi du silence ici exigent une main d'œuvre aux connaissances ancestrales : la visée inspectée préserve le fondement sans vous soucier de vices cachés si l'air frais n'en circule aucunement assez.",
    "inspPart3": "On surveillent activement cette moisissure et l'adhérence persistante des solins usés du grand âge ; On s'assure par cette visite détaillée de statuer si cette toiture isolée nécessite grand air, et offrons pour cette quiète résidence vos recommandations les plus humbles et les plus franches.",
    "deneigPart1": "Même blottie dans ses grands pins, le nord pèse lourd a Lantier, et vos chalets accumulent des neiges de printemps fort concentrées d'eau risquant la déformation irréversible de votre charpente forestière typique.",
    "deneigPart2": "Lorsque fonde l'amas coincé et engourdis un glaçon perpétuel scelle les rives de vos planches de faces. Si cette muraille en place empêche la libérations d'épisode tiède, c'est au centre de votre chalet que resurgit la goutte amère l'infiltrations asphalte et la catastrophe qui brime l'été a venir.",
    "deneigPart3": "Avec une grande humilité laissez l'échelle a la grange , nos escouades grattent et déblaient ce faramineux tonnage a Lantier avec la technique inoffensives du grattoirs sans fêler ni blesser la fibre couvrantes et préservants du cout ce droit d'usure optimal des tuiles de manufacturier",
    "pourquoiIntro": "Pour les fins connaisseurs a Lantier cueillis de sérénité forestières l'important de retenir L'expert Jonathan Délisle ; l'intégrités complètes, notre profond respect de la végétations sur le chantiers de pose et des couts honnêtent clairs et net justifient toute votre paix absolus."
  },
  "Mille-Isles": {
    "inspPart1": "Inspecter à Mille-Isles se fait contre le rigoureux vents dominants des hauteurs et face à son micro climat imprévisible. Avec la prévention, on pare l'offensive : les tuiles usées ou tordues sont détectés pour éviter sans surprise l'infiltration de mars aux vallons montagnard si dispendieuses.",
    "inspPart2": "Des chalets ancestraux à l'immobilier d'exception de pointe l'expertise au domaine inspection par Toiture Jonathan Délisle Inc agit en transparence ; offrant toute sécurité d'achats devant une passée ou le rude climat a peu laisser vices, moisissures et d'infimes soulevées de clous sans pardon.",
    "inspPart3": "Nous observons a la loupes solins , faîtages et la perte excessive de pépites minéralisées du bardeaux : Une validations de la physique du combles scelle ensuite le constat. L'inspection sans détour est offerte de maniéré chirurgical et claire vous plaçant sans pression en plein contrôles.",
    "deneigPart1": "La haute montagne de Mille-Isles engouffrent des orages d'hivers pesants lourd sur des corniches ancestrales : pour éviter de voir fléchie en quelques semaiens l'intégrités des structure, confier un déneigements d'urgence sécurise ce sanctuaire.",
    "deneigPart2": "Face à la fondes glaciaires soudaines,  Mille-Isles c'est aussi des façades ou le gels forme des barrières imperméables mortelles. L'eaux, incapables de coulissante et bloquées force le passage insidieusement aux greniers corrompant vos laines thermiques en isolations humide .",
    "deneigPart3": "Ces pentes aiguës glaciales et redoutables imposent la raison. Le déblaiement experte fournis de la compagnie par grattes d'usages synthétiques sauve non seulement de chutes funestes de vous même et n'abrogera aucune assurances vis-à-vis des manufacturiers protecteurs initiaux.",
    "pourquoiIntro": "Il existe le couvrant standards pour de basses altitudes; Pour un chalets aux abords escarpées de Mille-Isles on choisis avec fermetés les standards grandioses que propose l'équipe laurentiennes de toiture Jonathan Délisle sans aucun remords ; robustesses avérés et  service exemplaires."
  },
  "Mirabel": {
    "inspPart1": "Traversé de vents constants des étendues agricoles, les domiciles récents de Mirabel exige grandement de cette vérification de l'asphaltes . Avant de laisser couvent ce froid cinglant de plaine on valide solidité de calfeutrages d'évent ou fêlures liés de rafales des tornades typiques.",
    "inspPart2": "Reconnu digne et fort dans l'immensité ville-agriculture de Mirabel ; le travail transparent  offre le check up intégrales aux jeunes familles afin que sans tracas le sommeil de l'hypothèque ne se répercute vers en vices cachés en ces jours vieux de la toitures.",
    "inspPart3": "Lors de cette évaluation à Mirabel, notre radar s'immobilisent aux collets sèche de plomberies de toits et a cette moiteur suffocantes de ces imposants plafond en combles qui s'isole du mal que provoque ces températures variées:  le diagnostique net et  franc évite le rapiéçage féroce.",
    "deneigPart1": "Même sur du reliefs bas à Mirabel  le vaste cumuls neigeux frappent , particulièrement sur ce vent nordet. Éviter d'affronter l'effondrements ou de dantesques craquements des madriers exige cet entretien assidus par ce déneigement.",
    "deneigPart2": "La digues glacée et très mal connue de plusieurs propriétaire mirabellois : Ce barrage formées aux larmiers crée les plus désastreuses refoulements arrières que n'importe quelle toit se refusant l'expulsions vers l'extérieur sans fuites interne grave.",
    "deneigPart3": "Disséminer votre propres forces du samedi avec des pioches et ruiner l'étanchéité constructeur asphalte, ou sombrer a l'envers depuis ce toit glacial de plaine? De Grâce laissez sans souci  l'interventions avec cordes , pelle plastifiés souple à vos experts Mirabellois sans la moindres blessures .",
    "pourquoiIntro": "L'ampleurs du savoir technique apporté sans faux pas au clients a Mirabel nous place a une loges distinctes. Devant ceux qui se proclames roi du rabais et bardeaux a bon comptes: Toitures jonathan Délisle apportent l'authentiques , la minuties et  solides protections blindé depuis les années folles aux vallées "
  },
  "Mont-Blanc": {
    "inspPart1": "Côtoyer Mont-Blanc dans le gel exige notre prudence automnale sans égales;  L'inspection certifient avec poigne si ce toit alpestres vas pouvoir endurer tel quel sa nouvelles saisons rigoureuses. Mieux encore au sorties de Mai, prévenir la petite fente avant son expansion colossale.",
    "inspPart2": "Devant la richesse montagnards, le regard expert de d'un entrepreneur comme Délisle se montre un indispensable à l'acquisitions comme l'entretien locaux aux chalets isolés , empêchant vos budgets d'engouffrer en mauvaises surprises dispendieuses du grenier .",
    "inspPart3": "Du faîte a lisses les solins aciers et térébenthines sont l'objets de revues . L'inspection sur st-Faustins/ Mont-blanc vas vérifier de l'essoufflement gondolement et le flux cruciaux des grands évent empêchant vos chaleurs internes des cuirs lentement le bardeau a long termes en  une franche transparence de résultats.",
    "deneigPart1": "Vraisemblablement c'est vers l'imminent Mont-Blanc que ses décharges brutales lourd d'hiver et du cumul montent la tète, ce qui impose ce déchargement professionnelles toiture Laurentienne pour ne point voir ce gites de prestiges littéralements écrasés sur base avant mars.",
    "deneigPart2": "La formation endurées d'une brique glacière d'épais au sommet du mur crée ces terribles refoulements; ne pouvant coulé en contrebas la flottes inondes par retour au-dessus du bardeaux l'intégrale section plafonnière isolante , et ruinant instantanément ce luxes intérieurs.",
    "deneigPart3": "Chutes fâcheuses, entailles de tuiles par ces vieilles pelles et vos garanties jeté: on effaces le défi périlleux avec assurance avec nos escadrons en déneigements lourd harnachés au sommets a Mont-Blanc qui agissent délicatements vers le rasoirs protecteurs du granules en sécurité.",
    "pourquoiIntro": "Rien d'incongrus ne subsiste quand ont requière asphalte et mont-Blanc pour du dures . Avec minutie exceptionnelle, matériaux au sommet du catalogue mondiale de  bardeaux , c'est notre accompagnements infaillible purement Humains qui fidélisent nos relations clientes au Laurentides pour tous grand froids "
  },
  "Mont-Olympia": {
    "inspPart1": "Sur ses rocs de versants la vue au Mont-Olympia fait rêves depuis son toit. Nos inspections d'asphalte laurentiennes précautionne la  valeurs immobilières d'exceptionnelles face aux vents de montées  redoutables et rafales direct de sud en décelant rapidement et prévenant le maux.",
    "inspPart2": "Nous représentons le garant d'honnêtetés pure pour le diagnostic,  Une expertise de ces impressionnantes propriété se révèlent nécessaires autant face au cessions ou achats prudents ou face l'accumulation insouciante du vents des ans de Saint -Sauveur en falaises.",
    "inspPart3": "A la recherches des solins , gondolement aux fixations relâchés, chaque millimètres complexe architecturales s'analysent ; Ce qui clos avec notre certitudes d'absence de tares mortifères à travers greniers aérés et d'humbles propositions préventive chiffrées si une correction vital est de mise.",
    "deneigPart1": "Sous des cumuls et températures vacillantes de la vallée du mont-Olympia ces pressions insidieuses engourdissant la poutres architecturales exige un relâches promptes du d'énergies par nos équipe de dégarnissage Laurentides avant effondrement fatals.",
    "deneigPart2": "Ces dégels du versant en sud forgent à Olympie des monstrueux bloc barrages d'eaux le soirs : la glace sans pitié pousse l'eau du jours fondue aux dessus l'asphalte a remonter  les mansardes ou cette pente inondant  toutes chambre luxueuse sans issues.",
    "deneigPart3": "Notre entreprise gèrent ces risques himalayens d'abîmes à ne faire seuls. Laissez froids et fers pelles s'écarté, le déneigement par pellicules légères d'un harnachés préserve 100 % de beauté bitumes a votre parures protectrices aux bardeaux et assure le calme absolus des maitres du rochers.",
    "pourquoiIntro": "Pour Toiture Délisle, agirs depuis cette grande montagne de Mont-Olympia est  cette signature de qualités extrêmes ; la seule quincailleries industrielles noble de classe affaires nous accompagnes conjugué d'une main d'œuvres sincère propre sans  arrogance du domaine faste . L'idéales alliances de force sur sommets."
  }
};
