export const SERVICES_BATCH_1: Record<string, any> = {
  "Amherst": {
    "posePart1": "Le remplacement de bardeaux d'asphalte à Amherst représente une part importante de nos opérations, particulièrement pour les chalets construits il y a quelques décennies. L'évolution des matériaux nous permet aujourd'hui d'offrir des bardeaux architecturaux d'une résistance exceptionnelle, parfaits pour l'environnement forestier. Fini les vieux bardeaux qui se détérioraient sous l'humidité constante des sous-bois; nos revêtements sont épais, texturés et conçus pour repousser les assauts du climat laurentien.",
    "posePart2": "Notre approche à Amherst est d'une grande rigueur. Tout commence par le retrait complet des vieux matériaux pour exposer le pontage. C'est crucial : on ne peut poser un nouveau toit sur un contreplaqué ramolli par des années de condensation. Nos charpentiers remplacent toute section affaiblie pour assurer une structure parfaite.",
    "posePart3": "Vient ensuite l'étape clé de l'imperméabilisation : l'application d'une membrane autocollante aux endroits névralgiques (noues, cheminées, bordures). Dans un secteur comme Amherst où la neige reste tard au printemps, cette membrane est essentielle pour bloquer les infiltrations dues à la fonte. Enfin, nous optimisons la ventilation de votre entretoit pour garantir la longévité de l'installation.",
    "repPart1": "Malgré les meilleurs matériaux, une tempête imprévue ou la chute d'une branche dans les secteurs boisés d'Amherst peut causer des bris immédiats. Si vous remarquez des infiltrations d'eau après une averse ou des bardeaux abîmés au sol, notre équipe d'urgence intervient rapidement pour colmater les brèches et sécuriser votre chalet.",
    "repPart2": "Experte en réparation à Amherst, notre équipe trace le chemin de l'eau, souvent insidieux, depuis le toit jusqu'au plafond intérieur. Qu'il s'agisse de calfeutrage usé par le soleil, d'un solin défaillant ou de dommages liés aux forts vents locaux, nous remettons votre couverture à neuf de façon permanente, avec des bardeaux qui respectent l'apparence de votre maison."
  },
  "Arundel": {
    "posePart1": "À Arundel, la pose et le remplacement de bardeaux d'asphalte concernent autant les résidences de village que les bâtiments agricoles centenaires de la vallée. Les vents balayant les champs exigent des matériaux supérieurs. Nous privilégions les bardeaux architecturaux de haute densité, conçus pour se lier fortement et résister aux rafales impressionnantes de la région.",
    "posePart2": "Chaque intervention à Arundel débute par le déclouage total de l'ancienne toiture. Dans les maisons anciennes typiques du village, l'inspection du pontage (souvent en planches de bois plein) est primordiale pour repérer l'usure du temps. Nous consolidons les bases avec soin avant de procéder, car une toiture laurentienne ne pardonne pas les fondements fragiles.",
    "posePart3": "Nos couvreurs déploient ensuite notre système d'imperméabilisation de pointe. Les membranes posées sur les larmiers agissent comme bouclier contre les barrages de glace fréquents lorsque le vent de la vallée rencontre l'air chaud de la maison. L'optimisation de la ventilation, particulièrement sur les vieux bâtiments d'Arundel, fait partie intégrante de ce remplacement garanti pour les décennies à venir.",
    "repPart1": "Lorsque les vents dominants soufflent fort dans la vallée d'Arundel, il n'est pas rare de voir des bardeaux vieillissants se soulever. Si des matériaux se retrouvent sur votre pelouse ou si des cernes apparaissent au plafond, notre équipe locale est là pour une réparation immédiate, sauvant ainsi le reste de votre structure.",
    "repPart2": "Que lebris provienne de l'usure, d'un rongeur ayant cherché refuge ou de solins métalliques déformés par le cycle gel-dégel, nos experts ciblent la vraie source de la fuite. Nous effectuons des réparations durables et harmonieuses à Arundel, sans jamais masquer le problème sous du goudron temporaire."
  },
  "Bellefeuille": {
    "posePart1": "Le remplacement de bardeaux d'asphalte à Bellefeuille bat son plein, alors que les développements résidentiels des années 90 et 2000 arrivent à maturité. Les propriétaires de ces secteurs familiaux recherchent la tranquillité d'esprit, c'est pourquoi nous y installons des bardeaux architecturaux dernier cri. Faisant le pont entre la plaine et la forêt, ces revêtements épais protègent parfaitement contre les microclimats changeants.",
    "posePart2": "Notre expertise réside dans la préparation : nous retirons toute l'ancienne couverture jusqu'au contreplaqué pour inspecter la charpente de votre demeure à Bellefeuille. Un toit neuf posé sur un pontage en manque d'aération est voué à l'échec. Nous y portons donc une attention obsessionnelle en rectifiant le bois détérioré immédiatement.",
    "posePart3": "La sécurisation passe ensuite par la pose de membranes élastomères aux portions critiques (avant-toits et noues) pour empêcher la pluie ou le redoux hivernal de s'infiltrer. Nous veillons scrupuleusement à l'alignement précis des bardeaux et corrigeons le calcul thermique de votre entretoit par l'amélioration de vos sorties d'air, idéal pour affronter la chaleur estivale et le gel hivernal de Bellefeuille.",
    "repPart1": "Après une grosse bourrasque ou le passage d'orage de grêle dans la région de Bellefeuille, la réparation d'urgence est souvent de mise. Cernes bruns sur vos gypse ou arrachement partiel : nos équipes sont outillées pour colmater immédiatement les brèches afin que votre famille reste bien au sec en attendant l'évaluation des dommages complets.",
    "repPart2": "L'eau est un ennemi silencieux dans les demeures de Bellefeuille. Elle peut s'infiltrer autour d'un évent d'entretoit craqué et voyager le long de vos chevrons. Nos professionnels remplacent les matériaux défectueux par des options durables au ton agencé à votre toiture, pour une réparation toiture fiable et esthétiquement parfaite."
  },
  "Estérel": {
    "posePart1": "La pose de revêtement de toiture à Estérel est synonyme de chantiers haut de gamme. Les luxueuses résidences riveraines exigent des bardeaux architecturaux d'exception, souvent traités avec des algicides puissants pour repousser les lichens poussant dans l'humidité des lacs. Toiture Jonathan Délisle utilise les meilleurs matériaux disponibles sur le marché pour épouser l'architecture unique de votre domaine.",
    "posePart2": "L'attention aux détails à Estérel implique une réfection totale des bases : nous dévêtons la toiture avec une propreté de chantier irréprochable. Nos menuisiers examinent le pontage au-dessus de vos imposants espaces à aire ouverte, renforçant les sections qui ont souffert du microclimat lacustre humide.",
    "posePart3": "Nos installations intègrent une application surdimensionnée de membranes d'étanchéité, particulièrement là où l'eau pourrait être repoussée par les violentes rafales en provenance des lacs du Nord ou Dupuis. Chaque noue complexe et puits de lumière est blindé. L'aération est ensuite perfectionnée pour assurer que votre investissement immobilier exceptionnel à Estérel reste impeccable.",
    "repPart1": "Un domaine à Estérel, face à la météo agressive du lac, peut faire les frais de branches rompues ou de vents violents arrachant de vieux asphalte. Une infiltration soudaine n'est pas tolérable. Notre équipe d'intervention se mobilise rapidement pour sceller votre structure face aux éléments et éviter des dommages intérieurs catastrophiques aux finitions nobles.",
    "repPart2": "Nos réparations à Estérel prennent en compte la complexité des configurations de toiture en paliers ou en tourelles. Nous ne faisons pas de patchs temporaires : nous identifions précisément les solins problématiques ou les évents désuets pour reconstruire cette section du toit avec des raccords harmonieux correspondant au prestige de l'endroit."
  },
  "Lac-Supérieur": {
    "posePart1": "Effectuer le remplacement de bardeaux d'asphalte à Lac-Supérieur est l'affaire de couvreurs de haute montagne. Confrontées à une pression de neige faramineuse, les toitures locales doivent être cuirassées. Nous utilisons des bardeaux architecturaux lourds, fixés avec une densité de clouage supérieure, garantissant une inertie totale face aux vents himalayens qui s'engouffrent au nord de Tremblant.",
    "posePart2": "Chaque projet aux abords du Lac-Supérieur demande d'enlever avec précaution les anciennes tuiles pour valider la solidité absolue du pontage. Nous renforçons fréquemment la structure de bois (plywood) qui, dans ce climat alpin rude, a pu se courber ou se détremper lors d'hivers précédents où la glace s'est logée.",
    "posePart3": "L'étape de la membrane autoadhésive est ici portée à son maximum : nous en couvrons parfois une partie de la pente entière si le risque constructif l'exige. Ce bouclier d'hiver est l'ultime solution pour prévenir l'eau de fontes partielles de ruiner vos plafonds cathédrale. À Lac-Supérieur, notre système de ventilation repensé empêche le réchauffement des combles et la création redoutable de barrages de glace.",
    "repPart1": "La haute altitude de Lac-Supérieur n'épargne aucune toiture vieillissante. Dès qu'un dommage causé par le froid extrême, le poids de la glace, ou qu'une tuile s'envole lors d'une tempête, il faut stopper l'eau. Nos spécialistes de l'urgence sécurisent promptement votre chalet pour empêcher la moisissure de s'installer.",
    "repPart2": "Qu'il s'agisse d'un évent fendu par le froid intense de Lac-Supérieur, d'une lucarne mal scellée depuis sa construction ou d'un dommage de verglas, nous investiguons jusqu'aux fermes. Nous réparons la couverture en installant de nouveaux bardeaux et solins avec une technique anti-infiltration redoutablement éprouvée, vous redonnant la pleine sécurité."
  },
  "Lantier": {
    "posePart1": "Le remplacement de toiture à Lantier concerne souvent des chalets profondément enfouis dans la forêt, où l'humidité constante et le manque d'ensoleillement demandent des matériaux spécifiques. Nous employons des bardeaux architecturaux de la plus haute qualité, fortifiés de granules repoussant la mousse, qui prolongent la parure des résidences malgré l'ombre des grands conifères.",
    "posePart2": "Le premier travail à Lantier est de retirer l'asphalte altéré sans brimer la végétation précieuse de votre terrain. Une fois le contreplaqué apparent, nos couvreurs vérifient si l'humidité stagnante de la forêt a corrompu la charpente ancienne des chalets locaux. Nous remplaçons le bois pour offrir une véritable deuxième jeunesse à la maison.",
    "posePart3": "L'imperméabilisation est réalisée avec une pellicule vulcanisée ultra-résistante posée de façon stratégique à la base des versants de votre propriété à Lantier. Avec une forte présence de neige résiduelle l'hiver, nous blindons vos corniches. Nos méthodes rehaussent la durabilité tout en modernisant l'aspect esthétique grâce à un profilé de bardeau robuste et aéré.",
    "repPart1": "Au milieu des bois à Lantier, il suffit de la chute d'une lourde branche lors d'une tempête pour compromettre votre toiture. En cas d'imprévu météorologique laissant percer l'eau, il est impératif de nous contacter. Notre service de réparation agit vite pour éviter l'imprégnation de la laine minérale de votre plafond.",
    "repPart2": "Nos spécialistes pistent avec acharnement l'infiltration, qui parfois voyage loin sous le bardeau avant de goutter. Que ce soient les solins métalliques de votre cheminée déchaussés ou un collet de plomberie défaillant, notre réparation à Lantier se fait méticuleusement. Nous amalgamons les nouvelles pièces avec courtoisie à votre revêtement actuel."
  },
  "Mille-Isles": {
    "posePart1": "La pose de bardeaux d'asphalte à Mille-Isles intervient souvent sur des propriétés hautement escarpées et nichées loin des regards. Ce relief montagneux exige des bardeaux architecturaux hyper résistants à la flexion par le froid. Terminée l'époque des bardeaux fragiles qui fissurent, notre arsenal est pensé pour un environnement rude et isolé.",
    "posePart2": "Le défi à Mille-Isles est l'enlèvement minutieux de la vieille couverture en composant avec les variations d'élévation du terrain. L'examen du platelage qui s'ensuit est drastique; nous fortifions toute faiblesse du bois qui, autrement, s'effondrerait sous les bordées énormes typiques au sommet de ce secteur laurentien.",
    "posePart3": "Pour conjurer les infiltrations du printemps causées par l'épaisse couverture de neige têtue, nous couvrons une large proportion de la base avec des membranes autocollantes élastomères à haute adhérence. Ensuite, nous revoyons votre gestion des flux d'air: la ventilation corrigée chasse la chaleur du toit. Vos combles restants froids à Mille-Isles empêchent le gel fatal des corniches.",
    "repPart1": "L'hiver tenace ou un déneigement accidentel peut parfois briser des éléments de toiture sur un vieux chalet à Mille-Isles. Face à une fuite au printemps ou depuis qu'une rafale a dégarni votre faitière, nous intervenons en urgence pour refermer le bouclier protecteur de votre maison de montagne.",
    "repPart2": "Le chemin de l'eau est capricieux; une infiltration autour d'une vieille lucarne ou d'un solin en acier rouillé peut détremper l'intérieur s'il n'est pas traité. Notre savoir-faire répare l'intégrité de votre couverture à Mille-Isles avec de la menuiserie fine et des remplacements localisés de bardeaux, pour en finir de manière permanente avec la fuite."
  },
  "Mirabel": {
    "posePart1": "L'immensité de Mirabel se traduit par de vastes développements résidentiels familiaux où le remplacement de bardeaux bat son plein. Notre équipe répond à l'usure prématurée causée par l'absence d'ombrage et le soleil cuisant de la plaine avec des bardeaux d'asphalte architecturaux de nouvelle ligne, denses, réfléchissants et d'une durabilité exceptionnelle.",
    "posePart2": "Tout rénovation à Mirabel commande de mettre la structure à nu. Les premières phases de construction des années 2000 montrent souvent des détériorations aux panneaux d'OSB sous-jacents, particulièrement en raison d'une aération déficiente. Nous extirpons chaque particule gâchée pour vous recréer une base d'ancrage intègre, car la rigueur ne doit pas être optionnelle.",
    "posePart3": "La sécurisation des toitures de la région exige de contrer les incroyables bourrasques provenant des terres agricoles mitoyennes. Le clouage de nos bardeaux se fait selon une nomenclature éprouvée anti-typhon, et vos solins d'acier sont rivetés et collés pour survivre aux coups de vent inéluctables de Mirabel. La tranquillité s'installe alors par le haut.",
    "repPart1": "Les corridors de vent dans la plaine mirabelloise sont agressifs et un orage brusque de juillet n'hésite pas à écorcher des revêtements vieillissants. Si l'eau strie votre mur ou un arrachement d'asphalte laisse vos chevrons exposés, nous offrons une remise en état express pour barrer la route aux dommages dispendieux.",
    "repPart2": "En spécialistes des constructions modernes et classiques à Mirabel, nous traitons en permanence des défauts récurrents comme des scellants secs ou des évents (maximum) déplacés par les tornades laurentiennes. La vraie réparation ne fait aucun compromis : c'est un retrait et une pose à neuf de la zone accidentée, toujours assortie esthétiquement."
  },
  "Mont-Blanc": {
    "posePart1": "Remplacer le revêtement à Mont-Blanc (Saint-Faustin), c'est lutter contre la montagne. Les chalets de ski et les résidences aux abords du mont Tremblant nécessitent des matériaux supérieurs au standard de la plaine. Nos bardeaux architecturaux sont posés avec une résilience aux déchirements extrêmes pour résister aux énormes variations d'altitudes qui cisaillent la région.",
    "posePart2": "Nos charpentiers opèrent l'arrachement à Mont-Blanc avec la logistique inhérente aux abords des pentes. Une fois le pontage découvert, nous effectuons un sondage sévère du contreplaqué, puisque l'alternance pluie, soleil, verglas et neige de la municipalité détruit littéralement les maisons dont la fondation est humide.",
    "posePart3": "Déployer la sous-couche synthétique anti-glace sur les maisons de Mont-Blanc est un rituel d'une importance inouïe, surtout pour l'isolation des grands toits cathédrale communs ici. L'eau ne passera pas, et notre révision rigoureuse de vos évents veillera à expirer toute fraîcheur ou touffeur de l'entretoit pour garantir l'espérance de vie optimale du bardeau.",
    "repPart1": "Un poids exceptionnel de neige lourde à Mont-Blanc ou une tempête cinglante peuvent disloquer une section de toiture en quelques instants. Qu'il y ait des bardeaux fracassés éparpillés à terre ou des cernes d'eau fâcheux de fonte de neige, nos techniciens agissent en quelques heures pour redonner étanchéité à votre refuge alpin.",
    "repPart2": "Les infiltrations à Mont-Blanc se produisent fréquemment le long de la cheminée du foyer maçonné, ou par un calfeutrage fendu de lucarne. La mission d'une réparation est de retracer l'erreur et de substituer ce bris de façon pérenne en utilisant de la tôle fine, une membrane caoutchoutée et des dalles qui se fondent à l'existant."
  },
  "Mont-Olympia": {
    "posePart1": "A Piedmont, la pose sur les escarpements prononcés de Mont-Olympia fait appel à notre savoir-faire expert. L'architecture montagnarde typique de ses luxueuses maisons exige l'installation d'asphalte architectural dont les granules épaisses peuvent absorber les rayons des versants plein sud tout en supportant l'assaut hivernal de cette falaise pittoresque.",
    "posePart2": "Retirer une vieille, lourde couverture au flanc de Mont-Olympia, cela demande des artisans aguerris, équipés pour les pentes à forts angles. Tout le contreplaqué est judicieusement scruté. Les toitures grandioses ne valent rien sur du bois fragilisé; la reconstruction d'un support pur passe avant l'application de tout nouveau revêtement.",
    "posePart3": "Les barrages de glaces sont la Némésis des constructions étagées d'Olympia. C'est pourquoi Toiture Jonathan Délisle tapisse systématiquement d'épaisses lisières de membranes autoadhésives vos pourtours, en blindant chaque noue abrupte. Avec une ventilation réinventée propulsant la condensation au-dehors, l'harmonie d'un bardeau impérial protège votre superbe vue des airs.",
    "repPart1": "Au-dessus de la vallée de Saint-Sauveur, Mont-Olympia subit des vents thermiques ascendants violents. Un soulèvement des revêtements peut malheureusement poindre après un coup de vent hivernal. Si vos gouttières ou votre soffite sont imbibés, notre brigade est prompte à récurer le litissement et appliquer un pansement de toiture étanche sur-le-champ.",
    "repPart2": "Que ce soient des solins de cuivre anciens corrompus ou la mastication arrachée d'un puits de lumière ouvrant sur la vallée, notre mandat de réparation au Mont-Olympia est clair. Arracher la pathologie à la source et effectuer une micro-chirurgie de couverture garantissant qu'aucune gouttière ni vent ascendant ne pénétrera la majestueuse enveloppe de la maison."
  }
};
