export const SERVICES_BATCH_5: Record<string, any> = {
  "Mont-Tremblant": {
     "inspPart1": "Dominant la région par ses extrêmes climatiques, le Mont-Tremblant nécessite une inspection de toiture avec rigueur absolue. L'inspection préventive avant l'hiver sécurise le domaine avant les congères monstres, et celle de la fonte révèle avec précision les impacts de l'avalanche de verglas.",
    "inspPart2": "Être entrepreneur à Mont-Tremblant impose des standards internationaux. Notre transparence est votre plus grande force: que ce soit pour le refuge alpin ancestral ou les résidences luxueuses récentes, on détecte toute faille avant que l'or blanc ne fonde dans vos intérieurs.",
    "inspPart3": "Nous explorons tout: du calfeutrage des cheminées massives, aux joints de noues et l'état de la granulation. S'y greffe l'inspection rigoureuse de la ventilation pour confirmer que la complexe charpente respire, avec soumission franche et claire, sans la mondanité d'une vente inutile.",
    "deneigPart1": "Avec le record de précipitations neigeuses québécoises, Mont-Tremblant force le respect. Le déneigement de toiture n'est aucunement optionnel pour sauver votre charpente lourde de se déformer sous l'énorme et constant amoncellement du climat alpin.",
    "deneigPart2": "La bête noire de la station est la glace: la barrière de corniche provoquée par les chaleurs internes refoule l'eau de la fonte de gèle massif a contre-courant du bardeau et cause des infiltrations destructrices dévastant la noblesse de la menuiserie des chalets de luxe.",
    "deneigPart3": "Lâchez l'idée périlleuse de l'échelle instable en montagne; nos escouades de couvreurs acrobates déblaient ces tonnes en harnais sans accros. Surtout, la pelle de protection non-abrasive préserve intégralement l'asphalte et laisse opérer les clauses des garanties originelles de parures Tremblantoise.",
    "pourquoiIntro": "On choisit Jonathan Délisle à Mont-Tremblant par la pureté de la maitrise des hautes élévations. À cent mille lieues des offres de piètre qualité de sous-traitance, c'est de l'artisanat supérieur armé de bardeaux nobles, conjugué à l'honnêteté et la clarté formelle face aux défis d'une montagne prestigieuse sans pardons."
  },
  "Morin-Heights": {
    "inspPart1": "Au milieu des vastes conifères de Morin-Heights, le manque de soleil gruge les matériaux. Inspecter la toiture à l'automne éloigne le scénario catastrophe du bourrage mortifère des gouttières par d'acides aiguilles de pin, prémunissant contre la moisissure invisible.",
    "inspPart2": "Entrepreneur fiable de Morin-Heights nous veillons au grain. Notre diagnostic de l'enveloppe supérieure agit en filtre de vices cachés si commun sur le patrimoine immobilier ancien en pleine canopée ou pour d'un achat de chalet centenaire serein.",
    "inspPart3": "Notre œil piste ce gondolement ombragé des bardeaux, la lâche attache d'un métal de puits de lumière et l'épaisseur du bloc isolant respiratoire  des plus humides combles forestiers de façon à dresser une carte saine, nette et sans abus des correctifs potentiels futurs.",
    "deneigPart1": "L'encaissement de la forêt de Morin-Heights crée un coussin inébranlable pesant de très lourd fardeaux aux toits; Le service ponctuel de déneigement protège donc  vos espaces vastes d'une fracture net ou la fatales usures des appuis centraux du chalets au décennies l'hiver.",
    "deneigPart2": "Le micro climat encastré engendre l'eau stagnant le jours qui rebondit comme bloc d'un mur de glace à la brunante. Si l'accès coulant est scellé par cette digue; les remous vont sous le bardeau infectant gravement gypse et murs porteurs d'isolation d'infiltrations continues sans frein.",
    "deneigPart3": "Proscrit de la pelles rigides, notre déneigement au fond des bois par nos grattoirs souples préservatifs garantit qu'aucune friction ne ruine ce granits bitumineux. Nous sauvons des garanties au long court, sécurisant nos employés hautement attacher, loin des pirouettes mortelles d'un particulier courageux.",
    "pourquoiIntro": "Pour Toitures Délisle travailler la couvertures de Morin-Heights c'est  lutter d'adresse contre l'humidité constantes avec les pires calibres d'armures asphalte sur un esthétismes respectueux sans négliger d'y fondre la passion d'entreprise clair , méticuleuses laurentienne."
  },
  "Piedmont": {
    "inspPart1": "À Piedmont les impressionnantes pentes abruptes font rager l'exposition de votre toiture aux vents ascendants. L'inspection printanières ou avant neige  assure  que ces foudres n'ont pas brise les ancrages  ou laissés aux intempéries vos majestueux investissements intérieur a ces pics rocheux.",
    "inspPart2": "Un couvreur à Piedmont connait cette réalité en l'occurrence son œil intègre survis pour épargner des ruines causé d'une pathologie asphalte ou cernes ignorés, offrant aux acquisitions des grandes maisons en flanc montagne un soulagements absoluts transparents sur leurs capitaux de réserves.",
    "inspPart3": "Notre passage passeras en peigne la fixation extrêmes du bardeaux du sommet Piedmont ; On scrute de l'état des joints larmier acier, l'exausteurs aéraulique puis jusqu'l'humidité poignante potentielle du votre charpentes afin  que, devant la moindre révisions s'engage uniquement l'incontournable absolus franc.",
    "deneigPart1": "Sur un belvédère si escarpés de Piedmont, les fardeaux s'entasse dangereusement, Un déneigements en hauts lieux libères et  freines les menaçant poids extrêmes que subiront mortellement ces structure chics a air ouvertes aux saisons neigeuse capricieuses et humides de vallée .",
    "deneigPart2": "Un péril invisible, est cette glaciations meurtrière bloquante des chéneaux face au froid glacial. Si cet immenses redoux s'amorce l'eau coulé sous la toitures prisonnière de sa digue d'avant-toit glacé ravageant sans pitiés planchers de bois noble ou murs porteurs laurentien  par l'infiltration vicieuse.",
    "deneigPart3": "L'expérience périlleuse qu'est le verglas à l'échelle pour propriétaire est annulé . Le maitre couvreurs avec ses équipements d'altitude et racleurs protecteurs non acéré laisse sain un tapis fin neigeux  préservateur. Le manufacturier conserve ainsi  toutes garantie honorées sur l'usure a Piedmont et vous votre souffle .",
    "pourquoiIntro": "La verticalité complexe des demeures face a Piedmont  conviens idéalement aux forces techniques du couvreur Jonathan Délisle; Ce méticuleux artisan  alliés aux grand bitumes  mondiaux a fixations puissantes , et  engagements humains du respect des client en fond ce choix magistral régional incomparable "
  },
  "Prévost": {
    "inspPart1": "La succession de colline de Prévost donne des ravages à l'aveugle après sa bourrasque des corridor de vents forts. Procéder a de pointilleuse inspections  avant le grand blanc assure que tous arrachement discrets du calfeutrage soit scellés a point et épargnent des milliers aux frais.",
    "inspPart2": "L'honnêteté et la clarté avant la ventes pour un entrepreneur à Prévost permet  un soulagement absoluts , Ce checkup diagnostic du parc immobilières vallonné s'assure qu'aucuns soucis latent aux maisons de vieux bois ne brisera ce calme familiaux futur et l'intégrité couvrante .",
    "inspPart3": "Des pépites exfoliées  à l'entée d'eaux dures sur une cheminée et l'enclines gondolement causée des chaleur internes; On parcours la charpentes intérieurs et l'isolation respirant du combles : En finalité Prévost on y soumets notre  estimés juste sans poudre au yeux.",
    "deneigPart1": "Prévost et sa topographique dense attire l'immenses bancs et lourds amas neiges aux vallées grugés par pluie givrante:  Si la pesanteur mécaniques sévit, la toiture peut infléchir gravement et seul ce grand déneigements l'absout de tels fardeaux funestes au long terme.",
    "deneigPart2": "Face à la succession givre et dègels , cette barrière fâcheuse crée sur les avants-toits inondes sans failles dès février toute habitations . La digue bloque de glaces  oblige un lacs aux bardeaux et refoules insidieusement a vos sous platelage intérieur du précieux gypse .",
    "deneigPart3": "Ouvrons l'œil a Prévost et cessez acrobatie: Laissez aux experte poignes Toitures l'escouades harnachés rasant le fardeaux a grand coups de douces pèles spécialisée qui prévient l'annulations mortelles que l'usure ferreuse abimerai sur l'investissements asphalte premier sans exceptions aucunement .",
    "pourquoiIntro": "A ceux confiant quiétude et foyers au mains des faiseurs a rabais  Prévost, toiture Délisle répond diamétrales :  L'honnêtetés radical d'un services clients pur, du  savoir sur ventilation vallée complexe , aux clous et revêtements hauts gammes prouvent sans fausses manières ses grandeurs artisan ."
  },
  "Saint-Adolphe-d'Howard": {
    "inspPart1": "Véritable forteresse nordique a  St-Adolphe l'inspections d'une couvertures prévient d'atroce bris causé des climats subarctique hivernal en montagne. Nettoyer ou évaluer gouttières et solins automnales empêchent grandement le dégâts froids aux intérieurs dispendieux  de lisière .",
    "inspPart2": "Le gage des chalutiers immobiliers, C'est notre constats neutres intègres a St-Adolphe; de scruter  la pathologies fatals d'usures aux bardeaux et repoussé l'inondation surprise qu'éprouverai tout nouveau locataires ou le bon vieux propriétaires serein du lac.",
    "inspPart3": "Du  diagnostics on retire  la pertes minérales ; les fêlures aux évents, puis on va scruter cet intérieur glacial aux  entres toits ou un isolements pauvre s'y cacherais , nous transmettons un clair bilan sur l'états de santé sans obligation pour votre tranquillité au lointains.",
    "deneigPart1": "Les hivers sont bibliques à St-Adolphe;  Il est vital d'en déneigés les abords couvrants. Ce fardeaux monstrueux peut brisé chevrons  ou affaiblies toute fermes porteuses sur long termismes d'immenses dommage mécanique incommensurable du  vieux poids massif .",
    "deneigPart2": "Avec des températures glaciales l'eau d'évaporation gèle et forme la terrible Digue devant l'écoulement: La pente engorgé , et l'infiltrations massive ne peut coulissé. L'eau retourne  et s'enfuit en force destructrice derrière bardeau vers gypse, le bois et vider le portefeuille lacustre .",
    "deneigPart3": "Face aux pires précipice des toits ne montés aucunements par manque outils  souffrant ; Toitures Délisle maitrise  ses hauteurs de St-Adolphe. Outillés d'ancrages, balayant de douces lames polyuréthanes avec la neige au sol épargnas la couvrante de vos charpentes avec  pleines garanties manufacturés .",
    "pourquoiIntro": "Pour une solidités pures qui survis au géant frimas de Saint-Adolphe: le choix tombe aux faiseurs sincère Toitures Délisle , ou on ne conjugue du bardeau robuste des  lourdes marques reconnu s'associants avec une honnêtetés transparente au client comme socle solide de réputation ."
  },
  "Saint-Colomban": {
    "inspPart1": "Saint-Colomban vois d'immense développements de grande surfaces ou la préventions aux inspections allonge la belle beauté protectrice. Il en vas au devants avec ces vents violents plaine-foret : calfeutrages neufs, des gouttière a jour aux novembre, assure repos immenses avant blancheur gels.",
    "inspPart2": "Cimentés en réputation dans St-Colomban notre escouade offre constations de fait  et s'attache a protéger les fiers foyers familiaux naissants . L'usure accélérés se décelant a peines se dois de passer au filtre inspecteurs clairs sans aucun vices caches .",
    "inspPart3": "Tout passes au scrutions ; un bardeau ondulé, l'ancrages vicié de  cheminés par grands vents . Le diagnostic poussé du plafond mansarde révèle moiteurs de ventilations asujetis .Le rapports vous mets au nets ; sans fausses ventes aucunes ni tracas ou cout supplémentaire masqué.",
    "deneigPart1": "A st-colomban avec ce vents créants de la congères lourdes  massives ; Le services d'entretien en déneigement par ses experts toitures repoussent farouchement l'écroulement  lourds mécaniques de dommage a longue termes pesants sur ces vastes demeures familial grand planchers.",
    "deneigPart2": "Au grand périls, il y a formation de mures insulaires congelées. Ses immenses digues de glaces empêches a ce toit toute rejets . Les dègels massifs pousse la flottes d'infiltration aux rebords des murs sous les tuiles; inondants la laines pures et d'isolement au salon catastrophies sans pitiés .",
    "deneigPart3": "Refusés de risqués d'abroger vos contrats des concepteurs bardeaux avec outils contondant ou pire la chûte mortelles glace. L'escouade outilles sur sécurités d'attaches déblaies par le lègues fins neigeux protecteurs  en synthétique afin ne jamais faire failles aux garantis couvrantes du st-colomban et vous.",
    "pourquoiIntro": "Pour ceux à st-Colomban refusants l'ordianrire et misant a  qualités pures aux grand toitures complexes . On trouves chez Toiture jonathant Délisle une franchises  absolue de maitre sur la respirations et durabilités face a d'inégales bardeaux architecturaux robuste du monde entiers ."
  },
  "Saint-Faustin-Lac-Carré": {
    "inspPart1": "La météo crue du nord à Mont-Blanc (Saint-Faustin-Lac-Carré) oblige la plus pragmatique des inspections automnale: un bilan serré des solins avant l'assaut hivernal vous éloigne de conséquences hydroliques catastrophiques liées au froids.",
    "inspPart2": "Que l'on examine ce gite en bois ou la résidence d'attachement, l'examen transparent  fournit le contrôle totale a un propriétaire de St -Faustin éloignant grandement de ruines  dues a la passivité  aux vices cachées d'acquéreurs prévoyants .",
    "inspPart3": "Notre examen cible les gondolement, et les failles métalliques  ferblantières  devant du gel sévère pour aboutir a ce clair combles aérés afin d'éviter l'alimentation fongique des humidités et proposant humblement des options franc sans ventes forcé a personne.",
    "deneigPart1": "Ce haut lieux d'envergure dicte une précipitations massives d'hiver accablant; Afin préserver sa structures d'énormes poids insidieux sans retours sur l'axe central, un vrai déneigements d'ammoncelation s'affiche en pure maitre sauvetage de votre majestueux chalet .",
    "deneigPart2": "Le dommage le  plus infâmes au hivers alpin: La barrières glaciaires ou digues empêchant le flux d'assèchement couler le jours . Forcée d'aller vers amonts sous bitume l'eau s'écoule goulument perçant votre toitures  l'inondation détruits chaque éléments menuisiers intérieurs .",
    "deneigPart3": "Lâcher pèles lourde et échelle a glace , on délègues aux alpiniste en toitures du couvreurs la besogne st-Faustin. La tuiles conservent intègres et belles de ne pas se voir gratté au goudrons a vifs avec ses outilles polyuréthane fin ; et sauve d'une pertes pure garantis constructeurs .",
    "pourquoiIntro": "Pour faire barrières a ces tempêtes des lacs-Carré on ne s'offrent avec aucunes excuses moindres standards, et s'associe L'Artisan Délisle à un asphalte lourd mondialement certifiés . Son attentions humaines face  un cout final rigoureux  ferment complétements ces avenues rabais illusoire ."
  },
  "Saint-Hippolyte": {
     "inspPart1": "Vaste région humides des abords de lacs  , l'inspection préventive pour saint -Hippolyte combats violement moisissures organiques acides par une revues  d'automnes assurants au gouttières et calfeutreries  fissurés le passage serein sans orages dévastateur futurs  ",
    "inspPart2": "Un couvreur agis avec clarté nettes a saint-hippolyte protégeant propriétaires ou acquisitions devant les lourdes tare d'un boisements cachés afin faire disparaitre peur inopinées d'un gouffre au plafond et fiers investissements chalets en ruine .",
    "inspPart3": "Le passages aux crible s'effectue  : la fixations relâché d'aciers marins , perte du cuivres granulés ou l'analyses franches d'aire de ventilations greniers de ces domaines riverains : On livre le justes compte rendus clair en toutes honnêtetés ne point faiblir votre comptes portefeuilles sans besoins",
    "deneigPart1": "Saint Hippolytes s'attardes a ces lourds bourrasque humide gélifiés : Sous peines d'intenses poids engorgeant sa poutre sans arrêts et faire gauchir ce toits  magnifique : On dicte le déneigements aux fins de secourir sans dégâts  ce chalets familiales .",
    "deneigPart2": "Ce mur infâmes sur rebord de toit de cette humidité est fâcheux la nuit; La digues de glaces scelles le flux au lac et inonde purements  votre combles isolantes a remonta sous de la lourdes pressions l'eau printanière ; Un réelles désastres financier d'assurance .",
    "deneigPart3": "Il est irréfléchie sur pente givré de tentés avec haches ou racloirs de métaux l'impossible. Toiture Délisle sécurisés par de hauts harnachements gère a saint hippolyte de douceur polymère un fins recouvrements qui préserve 100% granulosités asphalte constructeur sauve et entières ",
    "pourquoiIntro": "Ceux retenant nos service a St-Hippolyte savantes notre connaissance de ce vents humides des lacs y conjugué au grandes classes de bardeaux traitées résistantes et  à valeurs clair humaines dans le devis clouant les offres des marchands d'aubaines du coins . "
  },
  "Saint-Jérôme": {
    "inspPart1": "Les grands foyers de Saint-Jérôme en capitole des secteurs  demandent récurrences de check-up d'inspections : Nettoyer des  vieux feuilles d'automnes aux quartiers matures  ou de vérifications d'un froids secs de canicules usants garantissent la vie d'asphalte par décennies complètes.",
    "inspPart2": "Transparents sur la grand places jérômienne l'entrepreneur vérifies votre couvertures pour contrecarrer les couteux scénario surprises des vieilles résidences patrimoines et d'un immobilier foisonnant  qui rassure tous grand acheteur a ce maitres artisans couvrants.",
    "inspPart3": "Un œille attentifs est prêtes aux gondolement asphalte  soleils, solidités chevrons , et calfeutrage des massifs cheminée st-jérôme . On valide aérations des grenier devant ces chaleurs écrasantes d'aout afin posé francs et intègres ce bilans juste et sans hautes pressions sur cout d'éventuelle soumissions.",
    "deneigPart1": "Cités denses ou les congères et lourds neiges d'urbains de Saint -Jérôme engoue le haut du batis ; pour échapper de plies la toitures aux énormes fardeau mécaniques des mars gélifiés, le déneigements devient se garderie salvatrice du bâtiments porteurs.",
    "deneigPart2": "Il se crée par des dègels de fâcheux murs bétons de glaces la nuits: ces digue étanche en bas du toit engendre amont inondatoires refoules et perces le bardeaux vers la douce pièces et chaleurs gypse causants de fatales moisissure sur charpente et dégât totalisants.",
    "deneigPart3": "On bannis les expéditions amateurs qui glisse au grand urbain: avec de l'encordages de professionnels a ST jérome les équipes opère au moyen plastique doux sans frictionnés a vifs les tuiles bitumes qui annulaire des heures de validités de vie et garantie usine pour la  toiture couvrante .",
    "pourquoiIntro": "Fuyant le bas prix éphémère un  client st-Jérôme de Jonathan Délisles s'offre  cette assurances de qualité pures urbaines: Matériaux architecturaux de la pus grande facture , transparence d'estimés , d'intégrités des chantiers aux millimètres près et politesses franches sans fausses apparats ."
  },
  "Saint-Sauveur": {
    "inspPart1": "Saint-Sauveur , mecca majestueuse et bourrasques constantes  oblige l'entretien inspections avises: En automne ont vide de la gouttières l'engorgement et scellés solides devant l'hiver, prolongeant d'espérances immenses tout beaux atours asphalte de ce si denses lieu valée.",
    "inspPart2": "Notre rigueur sans tares a ce postes maitres couvreurs a St -sauveur assure a propriétaire d'acquisitions fastes la clarté absolu aux rapports empêchants ces ruines en vices cachés de l'orographiques rudes afin dormir calme et confiant sans réelles surprises des toits.",
    "inspPart3": "Du haut du rocher  nos regards scruteront ce faite au cheminées luxueuses  ses solins tordus du vents ou des granulations fatigué et s'encre a vérifier le sains souffles du plafond pour soumettre sans attrapes l'une de si francs évaluations immobilières ne dictant l'actions  que sur vérités . ",
    "deneigPart1": "Sur un belvédère si escarpés de vallées st Sauvant, les fardeaux  d'un amassement colossal s'entasse dangereusement, un soins déneigements libères des fatal poids que subiront de l'effondrements complet ses magnifiques architecture du chalets grandioses ",
    "deneigPart2": "Son plus grands vices : barrières  ou murailles glaçons corniches dû a dègels répétés,  La eaux refoules insidieusement sans s'égoutta sur lac vallées. S'accumulant en pressions sous bardeaux  et noies tout intérieur gypse en froids destructions totales.",
    "deneigPart3": "Bannis d'outil a fendre ou s'esquinter ; La spécialités équipe d'acrobates Harnachements procèdes au douceur non agressives préservant saint de l'arrachés le bardeaux. On y conservent toutes usines aux normes pour qu'aucun ne sois de chutes avec la tranquillités du sommets st sauvois pure. ",
    "pourquoiIntro": "Devant se chics lieux l'on s'écarte de bas des  appels illusoires et toitures jonathan délissle assume a saint sauveur la pleines maitrises avec hautes courtoisies , bardeaux d'exception en  renommés pures de vents et froids de vallées afin solidifier en grand un prestiges de couvertures régionales."
  }
};
