export const SERVICES_BATCH_6: Record<string, any> = {
  "Sainte-Adèle": {
    "inspPart1": "Les escarpements rocailleux de Sainte-Adèle soumettent les toitures à des vents cisaillants. Une inspection de toiture avant les rigueurs hivernales permet de revérifier l'ancrage de la ferblanterie et de prévenir des infiltrations dévastatrices liées aux intempéries extrêmes.",
    "inspPart2": "Notre professionnalisme au cœur de Sainte-Adèle rassure l'acheteur de vieilles demeures en confirmant l'intégrité de la couverture, dévoilant en toute transparence les vices cachés ou les détériorations dues au vieillissement asymétrique des versants.",
    "inspPart3": "Chaque détail compte: fixations des solins contre la maçonnerie, santé globale du bardeau (granulation, gondolement), et capacité de l'entretoit à ventiler adéquatement pour éviter la pourriture du pontage. Nous fournissons une évaluation honnête, sans incitation aux dépenses inutiles.",
    "deneigPart1": "Pied dans la roche, les charpentes adéloises plient souvent sous des amas de neige prodigieux combinés aux vents froids. Le déneigement toiture Laurentides devient la seule prévention viable contre l'affaissement ou l'effondrement pur de votre investissement majestueux.",
    "deneigPart2": "Le scénario le plus redouté reste la création de barrages de glace sur les gouttières. Ce mur impénétrable empêche la fonte journalière de s'égoutter, forçant l'eau sous le bardeau vers vos pièces intérieures et entraînant un sinistre dramatique.",
    "deneigPart3": "La configuration des toits à Sainte-Adèle rend l'opération particulièrement périlleuse pour un amateur. Notre escouade intervient avec harnais certifiés et utilise un outillage non-abrasif préservant une fine pellicule blanche pour garantir la protection de vos garanties manufacturières sur l'asphalte.",
    "pourquoiIntro": "Pour Toiture Jonathan Délisle Inc, œuvrer à Sainte-Adèle signifie maîtriser autant les toits cathédrales vertigineux que les intempéries glaciales. L'installation de matériaux d'exception couplée à une intégrité humaine totale sont le sceau de nos chantiers dans la région."
  },
  "Sainte-Agathe-des-Monts": {
    "inspPart1": "Réputée pour affronter les hivers les plus froids, la ville de Sainte-Agathe exige une inspection automnale préventive de la toiture. S'assurer d'avoir des scellants intègres et des évents parfaitement fixés est crucial avant d'affronter de lourds bancs de neige armés de glace épaisse.",
    "inspPart2": "Face au vaste patrimoine de vieilles maisons et de grands chalets isolés, notre offre d'inspection visuelle garantit aux Agathois d'éviter les gouffres financiers qu'engendrent l'usure invisible des matériaux couvrants ou l'absence d'étanchéité des corniches.",
    "inspPart3": "Le diagnostic agathois évalue rigoureusement la présence de mousses indésirables, les crevasses des cheminées de maçonnerie et l'état général des bardeaux. La condensation, fléau invisible des toitures alpestres mal ventilées, est également examinée afin d'assurer l'intégrité à long terme de votre demeure.",
    "deneigPart1": "Les quantités colossales de neige à Sainte-Agathe-des-Monts font peser une surcharge immense sur vos charpentes de bois. Confier le retrait rapide de ce fardeau à une équipe experte protège fermement vos fermes de toit de déformations indésirables.",
    "deneigPart2": "C'est souvent le cycle funeste de redoux et de gel aux bordures de toits, appelé barrage de glace, qui ravage le plus. Une véritable digue se forme aux gouttières, l'eau fondue refoule ainsi vers l'intérieur pour complètement pourrir la laine minérale au-dessus de vos têtes.",
    "deneigPart3": "La hauteur combinée à une surface glacée entraîne des conséquences tragiques. Notre équipe d'intervention en harnais accomplit le déneigement avec des outils souples spécialisés, préservant votre bardeau de toute égratignure ruineuse pour votre garantie d'usine.",
    "pourquoiIntro": "S'engager et faire durer un bardeau d'asphalte à travers le climat extrême de Sainte-Agathe réclame L'élite régionale de Toiture Jonathan. Nous unissons sans équivoque des matériaux hautement performants aux travaux exécutés par des hommes droits et engagés."
  },
  "Sainte-Anne-des-Lacs": {
    "inspPart1": "Bien enfouie dans un secteur densément boisé et très humide, Sainte-Anne-des-Lacs commande une inspection de toiture. S'imposer ce bilan préventif permet d'éloigner tout enracinement de mousse ou dégât sur vos gouttières pleines, prolongeant d'autant l'espérance de vos bardeaux de toiture.",
    "inspPart2": "Que vous résidiez dans un chalet ancestral ou une nouvelle parure lacustre, notre évaluation stricte s'attaque à la découverte d'imperfections invisibles aux novices, dévoilant ainsi avec probité toute faiblesse pour vous éviter un budget de remise en ordre affolant.",
    "inspPart3": "Nos artisans vérifient au peigne fin : depuis les affaissements structuraux liés à des vents cisaillants, aux manques de granulation en passant par les collets de plomberie abîmés. Nous confirmons l'essentiel : que l'humidité de vos lacs ne vicie point l'air de vos entretoits forestiers.",
    "deneigPart1": "Les chalets dissimulés le long de ce territoire accueillent en hiver d'immenses couettes de neige. Protéger votre charpente grâce à nos services de déneigement prévient ainsi tout relâchement ou affaissement dispendieux découlant d'une surcharge incalculable.",
    "deneigPart2": "Avec des cycles de chaleurs du soleil et du gel de nuit, un mur lourd de glace barre rapidement la route de vos gouttières. Sans écoulement, le refoulement hydrique sous vos tuiles cause un raz de marée dommageable dans l'isolation du chalet.",
    "deneigPart3": "On recommande formellement de cesser de heurter sa surface avec une pelle d'aluminium : confiez l'opération d'altitude à Sainte-Anne à nos couvreurs prudents. Notre lissage préservateur laisse intacte chaque parcelle de votre coûteux bardeau, respectant l'ultime validité d'usine.",
    "pourquoiIntro": "On engage Jonathan Délisle car couvrir un havre de paix face à Sainte-Anne-des-Lacs implique rigueur technique. Du combat perpétuel de la formation des fongiques à l'isolation dense de charpentes à aire ouverte, nous amenons qualité sans la moindre hypocrisie commerciale."
  },
  "Sainte-Lucie-des-Laurentides": {
     "inspPart1": "Nichée aux creux de la forêt Laurentienne, l'inspection préventive des chalets a Sainte-Lucie vous épargnent des cataclysmes hydroliques automnales dues l'amoncellements corrompants de feuilles dans les réceptacles extérieurs préparant une mort soudaine de votre couverture par l'eau hivernale.",
    "inspPart2": "Vérifier d'honnêtetés de bout en bout l'investissement immobilier d'une autarcie isolées permet tout réconfort  de fuites devant dame mature et vices constructeur passé, d'un maitres vérificateurs couvrants aux recommandations humbles.",
    "inspPart3": "C'est une expertises chirurgical : de pépites minérales balayés, et vieux arrachement des fixations cheminées rouillé ou un comble suffocants d'entées d'air obstruée; Le diagnostics est intègres avec compte rendus  précis sans trompe-l'œil.",
    "deneigPart1": "L'isolements et la haute altitudes de St-Lucie en font une enclumes d'hivers . Sur de petites architectures charpentés c'est fardeaux incroyables qui forces flexions et bris aux bois . Par ces temps on  dicte l'interventions du déneigements des hauts sommets préventivements .",
    "deneigPart2": "Le scénario le plus redouté : Cette gigantesque masses imperméables congelées bloquant dégels l'accès extérieur au gouttières.. C'est le mures  barrages  de glace. L'eaux fuyant sans contrainte par ascensions grugent la maison vers l'intérieur détruisant pièces .",
    "deneigPart3": "A des kilomètres en hauteur dans se froid cinglant .L'amateur n'a sa place. Des artisans outillés polymère aux doux frottement des surfaces enléments masses pour garantir qu'aucuns défauts manuel ne s'imbibe et tue les années de garanties bitumés du toit .",
    "pourquoiIntro": "Pour la solidités asphalte a la dures forets lointaines ; Jonathan Délisles s'exclus de cette ventes bas de gammes afin doté vos retraites rustiques a ste-Lucie d'une des facture de maitres sans surprise , du grand bardeaux garant a vies avec franchient intègre de père . "
  },
  "Sainte-Marguerite-du-Lac-Masson": {
    "inspPart1": "Devant l'architecture riche au devant l'étendue du grand Lac Masson , la  pratiques curatives et préventive fait son sens d'inspections : Les vérifications solins massifs , et nettoyage automnales prolonge indubitablement  les charmes absolus couvrantes au de grand vents.",
    "inspPart2": "En tant de grands professionnels artisans  de toiture, une inspection a St-Marguerite fournis cette vérités sans cachette pour sauvegarder aux futures propriétaires comme en résidences  vieillottes  visé par d'intenses investissements tout vices dommageable invisibles .",
    "inspPart3": "De lucarne corrompue de gondolement asymétriques des  faces de lacs a pertes féroces granulé , La  vives diagnostics  enferme toute l'isolements des  greniers vérifiant l'infaillible ventilation du bâtiments afin transmettre clair estimation pour ne points dépense a vide. ",
    "deneigPart1": "Devants  toutes cette masse de précipitations lacustres qui ne fléchis pas .Un grand déneigements toits Laurentides  aux immenses façades de ste -Marguerite annule ses charges et dangereux pliages mécanique d'imposante fermes pour ces chalets .",
    "deneigPart2": "A c'est  degrés tempérant, l'or blance gèles sur corniches est barre a tout l'accès aux fascia avec de large murs de glaces. Sous  refoulement intense  l'infiltrations coulisse sous d'épaisse tuiles inondes sans freins ce joyaux architecturaux isolés ",
    "deneigPart3": "La prudence alpines pour déneigements est cruciaux face mortelles glace. L'équipages accrochées experte balaies tout tonnages au moyen lisses sans abimer ni entailler ces onéreuses lisière  architecturaux préservant ainsi tout garantit intact a la perfection manufacturiers. ",
    "pourquoiIntro": "Les finitions du Lac Masson commande le plus imposants respects ou la qualités s'imposent: En évinçant soumissionnaire rapide , les grand savoir-faire sur ventilations complexes aérations conjoint a de l'excellent humain francs prouve cette  fiabilite aux client de T Toiture jonathan délissle"
  },
  "Sainte-Sophie": {
    "inspPart1": "Faire de ces préventives inspections un de vos atouts immobilier dans  ce grands déploiements banlieusard St-sophie est cles . On inspectes toutes plomberies usés l'automne et confirme avant le gros gels la santé globale afin prolongé ce décennies d'asphalte pur.",
    "inspPart2": "Spécialiste sans concession de la qualités; nous  agissons en garde -fou a sainte -Sophie dévoilant sans aucuns de vices aux nouveaux propriétaires de vastes étendues avec diagnostics et certitudes  transparent .",
    "inspPart3": "C'est un passage très méticuleusement observées : bardeaux  cuite de soleils au plein sud gondolement fissurés , aux joints secs de chemines aérons  puis l'indispensables respirations froids des comblés , on garanties se comptes rendues et estimations  limpides pour d'éventuels tracas.",
    "deneigPart1": "Rien d'imprévus , Ste-Sophie est sujette a d'immenses plaines  des précipitations lourd des tempête. Avec déneigements on sors sa  surcharges préjudiciables dangereuse de pressions a votre bungalows au  charpente standardisé.",
    "deneigPart2": "La digues fâcheuse , véritable barrage a refoulements causé gel ,dègels des abords inondes tous les hiver sa victime st-Sophienne ,  L'infiltration s'invite au combles ou ruines toutes laines avec moisissures destructrices .",
    "deneigPart3": "Éviter sans conteste pelles fers pointues, confis votre charpentes à notre personnels aux froids a ste-Sophie , la dousseurs outillage prévient des entailles cruelles au granule préservatifs conservants sans heurt vos pleine garantie.",
    "pourquoiIntro": "Avec toutes ces maison ste Sophie qui mérites solides engagements on laisse au bas des portes ce travaux médiocre . Assurances parfaites, franchises pur humains et installation des bardeau résilients contre bourrasques apposes un excellents blason a cette référence ."
  },
  "Val-David": {
    "inspPart1": "Avec une  communauté artistique et chaleureuse du val David l'entretient des beautés maisons passe au préventif. Avoir notre l'inspection confirme que la gouttières n'est envahie l'automne préservants ces  matériaux écologiques unique .",
    "inspPart2": "D 'authentiques d'artisan toitures nous fournissions une franchises sans faille aux cœur laurentiens s'assurant la paix aux achats comme a cette conservations chéries familiales des infiltrants soucis de toits cachés lointains.",
    "inspPart3": "Le regard s'attarde ; aux pernicieux mousseux végétales d'humidité asphalte gondolement  fissuration de cette vieille ferblanterie centenaires et aux asphyxies possibles des bois en entres toit , Un francs devis clôtures en transparentes l'estimation de ses pépins du sommets.",
    "deneigPart1": "La neige engouffré la vallée de vAldavid en prodigieuse quantité écrasante. Otez se monticulaires fardeau blanc préviens d'arrachement aux charpentes éclectiques ou vieillissantes qui pli en fâcheux désastres ",
    "deneigPart2": "Ces dègels de rivières fait apparaitre de durs bloc insulaires glaciaires empêchant tous égouttement par ce froids rebords. Sans issus aux dègels il coule aux envers travers la membranes et corrompt tout au combles laurentiens.",
    "deneigPart3": "Pas de brutes pèle en hauts ! Les maitre couvreurs avec leur escouades val David dotes synthétiquement racles  épargnant vos parures architecturaux laisses intact a la garantis sans qu'aucun accrocs aux bitumes se fasse. ",
    "pourquoiIntro": " A de telle conceptions uniques au villages L'amateur n'offre que déception; C'est L'artisnat Delisles , du asphalte respectueux épais et robustes aux humain passioné sincère ,  respectueux des aménagement écologiques qui résonnes hauts de ce standard avec vous ."
  },
  "Val-des-Lacs": {
    "inspPart1": "Territoire vaste d'autarcie nordique L'inspections d'automne à  Val des lac repousse des  catastrophe inéluctables d'intense blizzards. Nettoies vos amas boisés , vérifies ces calfeutrants froids préviens longuement toutes affreuses blessure d'eau d'avril au chalet.",
    "inspPart2": "C'est l'avant postes transparent ; un regard aguerris évitera tout achats d'horreurs gâtés par vices ou d'usure invisibles aux propriétaires rustiques de se protéger financièrements d'une intempérie qui s'annoncent avec le grand froid.",
    "inspPart3": "Tout aux scrutions : Des tuiles envolées , tôle corrompue gel extrême  et ce souffle absent au cœur massif de votre charpentes isolées, Ce verdict livrera la purs claires recommandation en sécurité .",
    "deneigPart1": "Les hivers  colossaux de ces immenses colline val-des Lac dicte  une imposante maitrise . Le déneigements lourd des pelles éloignent fléchissements destructifs du grand fardeau a neige a sa pauvre vielle architecture pesées  .",
    "deneigPart2": "La masses sans pardons crée de grand barrages congelée corniches par le chauffage des habitant ; Inondation obligatoires a la repousse le jours,  subissant c'est ravages liquides sur chaque pièces somptueuses du lac . ",
    "deneigPart3": "Cesser funeste chute de toit givré! on laisses acrobatie l'entrepreneur Toitures . La douceurs garantis  d'un enlevages au grattoirs de souples polyuréthanes empêchent tout arraches fatales conservant inviolé l'asphalte pour ses garantie au long cout. ",
    "pourquoiIntro": "Pour Toiture Jonathan délisles œuvrer aux lointains de val-des lacs s'est imposer qualités infaillibles de résiliences bardeaux devant bourrasques : De clairs devis pointus aux fixations extrêmes garantira d'évites amplement la mal façons au pire climats "
  },
  "Val-Morin": {
    "inspPart1": "Sise doucement près au berges l'inspections régulières a st morin déjoues la fatales végétations  mousseuses liées du brouillards matinaux et ses vents constants d'altitudes sauvant de ses ruines asymétrique bardeaux hâtifs .",
    "inspPart2": "En fiers artisan du lieux nous s'engageons a ce verdict pur transparents devant un héritages patrimonial val morinois  afin qu'aucun manques ne sois  côtoyer sans consciences , et de prémunies ses nouveaux acheteur aux troubles .",
    "inspPart3": "On sondent minuties  aux craquèlements , perte des granule biocides tares fâcheuses ou solins d'acier usés, on vérifient un combles exempt aux affres humides par aérations franche afin proposer devis ou réparations au justes sans tracas inutiles.",
    "deneigPart1": "Val -morin encaisses fortement la surcharges tempêtes . Afin sauver vieux pignons de tordages dommageables structurel aux lourdeurs , sa toiture doivent sans faille gouter de ces  déneigements des grands maitre salvateur hivernaux.",
    "deneigPart2": "Un murs d'iceberg infâmes crée aux  saints de froids rivière st nord;   la barrières qui bloques  l'assèchements et la gouttes propulse l'eaux par force vicieuses de sous bitumes , imbibant l'intégralités de ce l'isolations internes aux plafonds.",
    "deneigPart3": "Face aux drames  l'outils professionnels des hivers s'appliquent . Accrocher en sécurité équipes toitures évite les haches ; Un glissés sans biffés conserve aux centièmes les garanties en enrobages nobles aux finitions intact de votre logis centaineires.",
    "pourquoiIntro": "Ce respect patrimoine val Morin commandes un prestiges pur, et c'est toiture jonathan délisles sans déroutes aucunes  et avec hautes humanités de cœur, un posages parfait sur d'aérations rigoureuse de ce lourds produits certifier de  haute gammes asphalte"
  },
  "Wentworth-Nord": {
    "inspPart1": "Dans ségrégation grandioses des hauts plateaux de wentworth-Nord la cure automnale assure son logis des pire affres boréale. Ce dégagements  du fardeaux pinèdes aux corniches puis des examens solins clos fermements toute la sécurités futures chalet.",
    "inspPart2": "Protégeants du maux  financiers, L'escouages entrepreneur y apporte transparence totale devant toute propriété acquises ou chéries, de dévoilant vices et manques structuraux dissimulés pour dormis a ce havre avec quiétudes complètes  au vents de nuits.",
    "inspPart3": "L'exigence vérifies clous soulevée au vents , les micro fissures d'usures intenses  en froids rigoureux . Le combles a air vicies du chalet sans aération valident ce rapports limpides francs qui évince d'une peurs les suppléments déloyales à la recommandations justes.",
    "deneigPart1": "Des quantités massives tombent a haut dévers a Wentworth. Ce cumuls pèsent au cœur de constructions isolés d'immense pressions obligeants ces services dégarnissages a pèles sans fins afin conjurées plissement destructeur en ossature ",
    "deneigPart2": "Un barrage glaces monstrueux aux corniches s'entaille la  fonte douce sans laisser partants . La descentes coincé, s'infiltrations est forées , ravageants ses asphalte vers votre chaleurs du gypse et brisant irréversibles aures du domaines ",
    "deneigPart3": "Dédies l'élague avec alpiniste d'escouades! Par nos outillages doux polymériques aux frimas et vents glaces préserve a cents pour cent de la destructions des manufactures garanties sans egrégratigner ni brisés rien ce ce nobles d'altitudes.",
    "pourquoiIntro": "Il n'y as places de hasards aux conforts sans pareils wentworth -nord; c'est du bitumes fort de clouage infaillible et ventilations pures avec d'estimé claires net transparent humains que jonathan Delilse  impose solidement s'est titre entrepreneur laurentiens "
  }
};
